### ISSUE TITLE
The proxy code do not fail nor write log when PHP's exec() function is disabled

### ISSUE THREAD

**Issue by lpoujol** [CollaboraOnline/richdocumentscode#100]
Hi

In the proxy.php file, there is no error catching if  PHP's exec() function is disabled
https://github.com/CollaboraOnline/richdocumentscode/blob/c204b0ff52ebceda6a733ee994eaecc7a17c0352/proxy.php#L73

It will behave as if the command started successfully and wait forever. In a loop :(

`exec()` may be disabled for a number of reasons, often on shared webspace.
It would be very handy to handle this situations more gracefully and have at least an error message written in Nextcloud logs

Also, this introduce an 'odd' behaviour as it makes ALL webpages slow on the nextcloud instance :(

**OS** : GNU/Linux Debian 10 (Buster)
**PHP** : 7.3.19-1~deb10u1
**Setup** : Nginx + PHP-FPM
**Nextcloud Version** : 20.0.4
**App Collabora Online** : 3.7.11
**App Collabora Online - Built-in CODE Server**  :  6.4.202

**Comment by timar** [comment]
I believe that commit ca085d53ec6e4cbe9dc3753340aaad3998ea1281 addressed this issue.

**Comment by timar** [comment]
I was wrong, it does not work.
