### ISSUE TITLE
Collabora doesn't load documents

### ISSUE THREAD

**Issue by simplynotes** [CollaboraOnline/richdocumentscode#104]
Nextcloud is 21.0.0 beta 6 on Ubuntu 20.04
Collabora server is 6.4.303

When trying to open a document I receive the following error (in German) 
"Lesen des Dokuments von Speicher fehlgeschlagen, Bitte kontaktieren Sie den Administrator Ihres Speicherservers"

the dokuments are stored on the same HD the Nextcloud instaation is on. 

Any idea how to solve / troubleshoot the problem?

thanks
![Bildschirmfoto vom 2021-01-20 21-35-40](https://user-images.githubusercontent.com/64169856/105231710-91c07380-5b67-11eb-8d4b-ef5b94e1fb2f.png)

**Comment by s-ailus2** [comment]
This happened on two systems I updated to Nextcloud 21 (Docker image). Richdocuments is 4.0.1. I also used the latest CODE, but the earlier one had the same issue. It would seem like the problem would be on Nextcloud side (Nextcloud itself or richdocuments, but I don't know which one).

Some more logs here:

{"reqId":"loaTjDfY8c59smhCQ6V6","level":3,"time":"2021-03-03T07:57:22+00:00","remoteAddr":"172.19.1.1","user":"--","app":"index","method":"GET","url":"/index.php/apps/richdocuments/wopi/files/31576_ocn4mu8p30vz?access_token=XXXXXXXXXXXXXXXXXXXXXX&access_token_ttl=0","message":{"Exception":"Exception","Message":"Call to a member function getUID() on null","Code":0,"Trace":[{"file":"/var/www/html/lib/private/AppFramework/App.php","line":157,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Richdocuments\\Controller\\WopiController"},"checkFileInfo"]},{"file":"/var/www/html/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Richdocuments\\Controller\\WopiController","checkFileInfo",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"fileId":"31576_ocn4mu8p30vz","_route":"richdocuments.wopi.checkFileInfo"}]},{"file":"/var/www/html/lib/base.php","line":993,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/richdocuments/wopi/files/31576_ocn4mu8p30vz"]},{"file":"/var/www/html/index.php","line":37,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","Line":159,"Previous":{"Exception":"Error","Message":"Call to a member function getUID() on null","Code":0,"Trace":[{"file":"/var/www/html/custom_apps/circles/lib/Api/v1/Circles.php","line":222,"function":"listCircles","class":"OCA\\Circles\\Api\\v1\\Circles","type":"::","args":[15,"",1,"",true]},{"file":"/var/www/html/custom_apps/deck/lib/Db/BoardMapper.php","line":172,"function":"joinedCircles","class":"OCA\\Circles\\Api\\v1\\Circles","type":"::","args":["",true]},{"file":"/var/www/html/custom_apps/deck/lib/Db/BoardMapper.php","line":94,"function":"findAllByCircles","class":"OCA\\Deck\\Db\\BoardMapper","type":"->","args":["sailus",null,null,-1,true]},{"file":"/var/www/html/custom_apps/deck/lib/Sharing/DeckShareProvider.php","line":697,"function":"findAllForUser","class":"OCA\\Deck\\Db\\BoardMapper","type":"->","args":["sailus"]},{"file":"/var/www/html/lib/private/Share20/Manager.php","line":1336,"function":"getSharedWith","class":"OCA\\Deck\\Sharing\\DeckShareProvider","type":"->","args":["sailus",12,null,-1,0]},{"file":"/var/www/html/apps/files_sharing/lib/MountProvider.php","line":82,"function":"getSharedWith","class":"OC\\Share20\\Manager","type":"->","args":["sailus",12,null,-1]},{"file":"/var/www/html/lib/private/Files/Config/MountProviderCollection.php","line":119,"function":"getMountsForUser","class":"OCA\\Files_Sharing\\MountProvider","type":"->","args":[{"__class__":"OC\\User\\User"},{"__class__":"OC\\Files\\Storage\\StorageFactory"}]},{"file":"/var/www/html/lib/private/Files/Filesystem.php","line":452,"function":"addMountForUser","class":"OC\\Files\\Config\\MountProviderCollection","type":"->","args":[{"__class__":"OC\\User\\User"},{"__class__":"OC\\Files\\Mount\\Manager"}]},{"file":"/var/www/html/lib/private/Files/Node/Root.php","line":379,"function":"initMountPoints","class":"OC\\Files\\Filesystem","type":"::","args":["sailus"]},{"function":"getUserFolder","class":"OC\\Files\\Node\\Root","type":"->","args":["sailus"]},{"file":"/var/www/html/lib/private/Files/Node/LazyFolder.php","line":66,"function":"call_user_func_array","args":[[{"__class__":"OC\\Files\\Node\\Root"},"getUserFolder"],["sailus"]]},{"file":"/var/www/html/lib/private/Files/Node/LazyRoot.php","line":41,"function":"__call","class":"OC\\Files\\Node\\LazyFolder","type":"->","args":["getUserFolder",["sailus"]]},{"file":"/var/www/html/custom_apps/richdocuments/lib/Controller/WopiController.php","line":672,"function":"getUserFolder","class":"OC\\Files\\Node\\LazyRoot","type":"->","args":["sailus"]},{"file":"/var/www/html/custom_apps/richdocuments/lib/Controller/WopiController.php","line":144,"function":"getFileForWopiToken","class":"OCA\\Richdocuments\\Controller\\WopiController","type":"->","args":[{"id":328,"__class__":"OCA\\Richdocuments\\Db\\Wopi"}]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":218,"function":"checkFileInfo","class":"OCA\\Richdocuments\\Controller\\WopiController","type":"->","args":["31576","XXXXXXXXXXXXXXXXXXXXXXXXXXX"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":127,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Richdocuments\\Controller\\WopiController"},"checkFileInfo"]},{"file":"/var/www/html/lib/private/AppFramework/App.php","line":157,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Richdocuments\\Controller\\WopiController"},"checkFileInfo"]},{"file":"/var/www/html/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Richdocuments\\Controller\\WopiController","checkFileInfo",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"fileId":"31576_ocn4mu8p30vz","_route":"richdocuments.wopi.checkFileInfo"}]},{"file":"/var/www/html/lib/base.php","line":993,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/richdocuments/wopi/files/31576_ocn4mu8p30vz"]},{"file":"/var/www/html/index.php","line":37,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/html/custom_apps/circles/lib/Api/v1/Circles.php","Line":202},"CustomMessage":"--"},"userAgent":"LOOLWSD WOPI Agent 6.4.6","version":"21.0.0.18"}

**Comment by s-ailus2** [comment]
This actually appears to be a problem with Circles. Have you tried disabling it?

**Comment by s-ailus2** [comment]
It helped here.

**Comment by maxdrfr** [comment]
Nextcloud 20.0.8, CODE Server 6.4.607 and Collabora Online 3.7.16 here.
Created ODT document, edited, saved, closed and reopened: comes empty !
Re-edited, pushed save button and get same error like @simplynotes 
![image](https://user-images.githubusercontent.com/17526713/110376281-4c8ecd00-8053-11eb-9a71-c43ce02cf807.png)

Is it the beginning of a nightmare ?

**Comment by mohe2015** [comment]
> Ok, after hours, Collabora act like before, no writing to nextcloud, documents stay at 1 KB size.
> Haven't solution.

Do you use the Circles app?

**Comment by maxdrfr** [comment]
Circles app is disabled.

**Comment by gitgt** [comment]
Hi, this was reported long ago, please write if you experience the same with new versions.

**Comment by ogmkp** [comment]
@gitgt It's works with new version, no more critical issue like this thread since my last comment.

**Comment by gitgt** [comment]
Thank you, let's close. I see that there were 2 more reporters here, but hopefully they resolved in 2 years.
