### ISSUE TITLE
Unable to install on arm64

### ISSUE THREAD

**Issue by deathblade666** [CollaboraOnline/richdocumentscode#106]
Hello I just tried installing the arm64 version with in instructions provided in the next cloud readme which states to run 
`sudo -u www-data php -d memory_limit=512M ./occ app:install richdocumentscode
`
Running this gives an error as it is for the x86_64 version. So i ran the following afterwards 
`sudo -u www-data php -d memory_limit=512M ./occ app:install richdocumentscode_arm64
`
and got the following error
`Error: App "Collabora Online - Built-in CODE Server (ARM64)" cannot be installed because the following dependencies are not fulfilled: The following architectures are supported: aarch64
` 
I am trying to install this on a Raspberry Pi 4 B running Raspberry OS lite. Please let me know if there is any other information that would be helpful

**Comment by joyinglee** [comment]
As far as i know,official raspberry os in the download page is 32bit because the old raspberry pi may don't support 64bit. There is a beta 64bit [https://www.raspberrypi.org/forums/viewtopic.php?f=117&t=275370](url) may work.

**Comment by almereyda** [comment]
The last link fragment of the*Collabora Online - Built-in CODE Server (ARM64)*
 app https://apps.nextcloud.com/apps/richdocumentscode_arm64 in the store suggests the name of the ARM64 version of the app is

    richdocumentscode_arm64

which can then be installed with

    ./occ app:install richdocumentscode_arm64

This is likely a documentation issue where the same description text is used for both builds of the extension, `aarch64` (=`arm64`, using the prior name is suggested) and `amd64`.

**Comment by deathblade666** [comment]
> As far as i know,official raspberry os in the download page is 32bit because the old raspberry pi may don't support 64bit. There is a [beta 64bit](https://www.raspberrypi.org/forums/viewtopic.php?f=117&t=275370) may work.

 I will double check, but I believe I am running the 64bit version

**Comment by deathblade666** [comment]
> The last link fragment of the_Collabora Online - Built-in CODE Server (ARM64)_
> app https://apps.nextcloud.com/apps/richdocumentscode_arm64 in the store suggests the name of the ARM64 version of the app is
> 
> ```
> richdocumentscode_arm64
> ```
> 
> which can then be installed with
> 
> ```
> ./occ app:install richdocumentscode_arm64
> ```
> 
> This is likely a documentation issue where the same description text is used for both builds of the extension, `aarch64` (=`arm64`, using the prior name is suggested) and `amd64`.
> 
> In my case this looked as follows:
> 
> ```
> # docker-compose exec -u 82 app ash
> /var/www/html $ ./occ app:install richdocumentscode_arm64
> richdocumentscode_arm64 6.4.403 installed
> richdocumentscode_arm64 enabled
> /var/www/html $ 
> ```

I did try that but it still failed. I'm going to verifying my OS is 64bit and will report back.

**Comment by deathblade666** [comment]
So I just checked, I am running 32bit which is most likely my issue. I guess I'll wait till 64 bit stable is released and migrate over to that.

Thanks guys
