### ISSUE TITLE
PHP 8 Support

### ISSUE THREAD

**Issue by sunjam** [CollaboraOnline/richdocumentscode#109]
Related to #108 php8 was introduced in v21.  Note 7.x will continue to be supported for now.  Thanks for the great app!

**Comment by timar** [comment]
@sunjam: What is the issue here? Is there something in proxy.php that is not compatible with php 8?

**Comment by sunjam** [comment]
Haven't had time to test yet.  Apologies if the issue isn't relevant for your app.

**Comment by timar** [comment]
No problem. In this case let's close the issue now. I think we are PHP8 compatible, because the script is so simple.
