### ISSUE TITLE
is there any way to change the port number from 9982 ?

### ISSUE THREAD

**Issue by glenb77** [CollaboraOnline/richdocumentscode#110]
i run tvheadend server which uses 9981 and 9982. is there any way to run the appimage from within nextcloud on a different port?

**Comment by timar** [comment]
AFAIK it's not configurable unfortunately. But I changed it to 9983, and we'll use it in the next release (in the coming days).

**Comment by af7567** [comment]
For some reason this change "killed" my web server. After few hours after updating to the latest built in CODE server my webserver stopped responding and I finally tracked it down to nextcloud/apps/richdocumentscode/proxy.php:283.
It was stuck in a loop trying to connect to port 9983 but loolwsd was still running on port 9982.
I uninstalled the app from nextclound, killed loolwsd, umounted the appimage, then reinstalled and it's all OK now :)
