### ISSUE TITLE
6.4.606 breaks Nextcloud integration

### ISSUE THREAD

**Issue by rschr** [CollaboraOnline/richdocumentscode#111]
After updating to 6.4.606, no documents can be loaded anymore. When trying, after a while the message "Collabora Online konnte nicht geladen werden - Bitte versuchen Sie es später noch einmal" appears (translated: "Collabora Online could not be loaded - Please try again later"), and there is this log entry:

Exception: Could not find urlsrc in WOPI
/var/www/nextcloud/apps/richdocuments/lib/TokenManager.php - line 217:
OCA\Richdocuments\WOPI\Parser->getUrlSrc()
/var/www/nextcloud/apps/richdocuments/lib/Controller/DocumentController.php - line 256:
OCA\Richdocuments\TokenManager->getToken("*** sensiti ... *")
/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 169:
OCA\Richdocuments\Controller\DocumentController->index()
/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 100:
OC\AppFramework\Http\Dispatcher->executeController()
/var/www/nextcloud/lib/private/AppFramework/App.php - line 152:
OC\AppFramework\Http\Dispatcher->dispatch()
/var/www/nextcloud/lib/private/Route/Router.php - line 309:
OC\AppFramework\App::main()
/var/www/nextcloud/lib/base.php - line 1008:
OC\Route\Router->match()
/var/www/nextcloud/index.php - line 37:
OC::handleRequest()

This is Nextcloud 20.0.8 with Apache/2.4.46 on Ubuntu 16.04.7 LTS server.

**Comment by rschr** [comment]
6.4.607 fixes it, although nothing is mentioned in the list of changes.

**Comment by AlfredSK** [comment]
I have exactly the same problem with that last two releases of the Nextcloud CODE App.

**Comment by timar** [comment]
> I have exactly the same problem with that last two releases of the Nextcloud CODE App.

Do you mean 6.4.702 and 6.4.703?

**Comment by AlfredSK** [comment]
Yes, exactly.

**Comment by AlfredSK** [comment]
I saw the code changes in those releases. There was something with adding 'index.php' to some paths.
So, I want to add that I use "prettified" URLs in Nextcloud - the .htaccess rewrite option to get rid of the 'index.php' part in Nextcloud's URLs. Just in case this is important.

**Comment by AlfredSK** [comment]
I have now manually downgraded to [v6.4.608](https://github.com/CollaboraOnline/richdocumentscode/releases/download/6.4.608/richdocumentscode.tar.gz). With this version it is working again.
Nextcloud 20.0.8
Collabora Online - Built-in CODE Server 6.4.608

**Comment by rschr** [comment]
I can confirm 6.4.704 isn't working for me either. The symptoms are the same as in my original report. I'll try to manually revert to 6.4.608, too.

**Comment by timar** [comment]
1. When "no documents can be loaded anymore" do you see thumbnails still? I.e. if you upload a new document to Nextcloud, will it have a small preview as thumbnail?
2. Can you please try in settings to click again to Built-in CODE server? Or have you tried to restart the webserver?
I wonder if this bug is related to https://github.com/nextcloud/richdocuments/issues/1441

**Comment by AlfredSK** [comment]
I will try this later today.

**Comment by rschr** [comment]
> 1. When "no documents can be loaded anymore" do you see thumbnails still? I.e. if you upload a new document to Nextcloud, will it have a small preview as thumbnail?
> 2. Can you please try in settings to click again to Built-in CODE server? Or have you tried to restart the webserver?
>    I wonder if this bug is related to [nextcloud/richdocuments#1441](https://github.com/nextcloud/richdocuments/issues/1441)

1. Yes
2. Built-in CODE server is reported as being installed and reachable. Restarting the webserver doesn't help.

**Comment by ilsawa** [comment]
I have 2 servers with different version OS (x86_64) and nextcloud.
1. Ubuntu Bionic, Apache/2.4.29, PHP Version 7.2.24, mariadb-server 1:10.1.47, redis-server 5:4.0.9, Nextcloud 20.0.8
2. Ubuntu Focal, Apache/2.4.41, PHP Version 7.4.3, mariadb-server 1:10.3.25, redis-server 5:5.0.7-2, Nextcloud 21.0.0
Both NextCloud installed from sources without dockers and snap.

On both servers after updating richdocumentscode to 6.4.703 does not open documents (https://github.com/CollaboraOnline/richdocumentscode/issues/118).
Documents began to open on both servers after I returned back richdocumentscode 6.4.702

**Comment by timar** [comment]
Would you mind re-testing with version 6.4.705?

**Comment by ilsawa** [comment]
> Would you mind re-testing with version 6.4.705?

It works

**Comment by rschr** [comment]
> > Would you mind re-testing with version 6.4.705?
> 
> It works

Confirming, works for me too!

**Comment by AlfredSK** [comment]
Confirmed. 6.4.705 works!

Thank you very much! :-)

**Comment by dspoel** [comment]
Running with CODE 6.4.705 and Collabora Online 4.0.4 that I installed from within my otherwise working Nexcloud installation. The CODE server cannot be reached and it turns itself off automatically, and as a result I'm getting time out messages. When selecting "Use your own server" it does not work, "Could not establish connection to the Collabora Online server."
