### ISSUE TITLE
richdocumentscode 6.4.703 - App is not compliant

### ISSUE THREAD

**Issue by ilsawa** [CollaboraOnline/richdocumentscode#118]
After updating richdocumentscode to 6.4.703 does not open documents:
"Failed to download Collabora Online - try again later✖️"

sudo -u www-data php /var/www/nextcloud/occ app:check-code richdocumentscode
Analysing /var/www/nextcloud/apps/richdocumentscode/lib/Settings/Admin.php
 1 errors
    line   41: == - is discouraged
Analysing /var/www/nextcloud/apps/richdocumentscode/proxy.php
 16 errors
    line   63: == - is discouraged
    line  127: != - is discouraged
    line  131: != - is discouraged
    line  183: == - is discouraged
    line  202: != - is discouraged
    line  210: == - is discouraged
    line  245: == - is discouraged
    line  254: != - is discouraged
    line  254: != - is discouraged
    line  301: == - is discouraged
    line  332: == - is discouraged
    line  337: == - is discouraged
    line  348: == - is discouraged
    line  363: != - is discouraged
    line  363: == - is discouraged
    line  386: == - is discouraged
App is not compliant

I trial reinstall:
root@nextcloud:~# sudo -u www-data php /var/www/nextcloud/occ app:disable richdocumentscode
richdocumentscode 6.4.703 disabled
root@nextcloud:~# sudo -u www-data php /var/www/nextcloud/occ app:remove richdocumentscode
richdocumentscode disabled
richdocumentscode 0 removed
root@nextcloud:~# sudo -u www-data php /var/www/nextcloud/occ app:install richdocumentscode
richdocumentscode 6.4.703 installed
richdocumentscode enabled

And I see the same mistake that at the beginning.

In apache2 logs:
[Sun Mar 21 15:25:42.766955 2021] [php7:notice] [pid 5625] [client IP:44910] richdocumentscode (proxy.php) error exit, PID: 5625, Message: appimage_not_executable

**Comment by ilsawa** [comment]
Rolled back to version 6.4.702-it worked

**Comment by timar** [comment]
Thanks for the report. 
* 'App is not compliant' -- this is not new to 6.4.703, you would get the same for 6.4.702. Worth fixing, sure. 
* 'appimage_not_executable' -- this is not fatal, per se. proxy.php tries to add the executable bit to the AppImage
The real problem is that upgrade to 6.4.703 did not succeed for you (probably the root cause is the same as in #111).
