### ISSUE TITLE
Cannot on a rasberry pi host:  `App Collabora Online - Built-in CODE Server (ARM64)" cannot be installed because the following dependencies are not fulfilled: The following architectures are supported: aarch64`

### ISSUE THREAD

**Issue by IanChok** [CollaboraOnline/richdocumentscode#123]
When trying to click on `download and enable` I get the following error: 
![image](https://user-images.githubusercontent.com/33184246/114490004-edc7f080-9bc8-11eb-863d-6a75c58050d5.png)

But my nextcloud instance is running in docker on a raspberry pi 4 which is ARM, right?

**Comment by marcosmartingm** [comment]
We have the same problem, we have architecture in 32Bits (armv7l).
PLEASE develop the server in arm 32bits = armv7l = raspibian stable. This version is not compatible with us :(

**Comment by timar** [comment]
It is not planned to port Collabora Online to 32-bit ARM, sorry.

**Comment by Oberlurch3000** [comment]
I have a issue/question related to this.
After switching the kernel of my pi4 to ARM64 I was able to install the CODE server and link it to the NC Office App.
When creating a textfile from template I get an error message: Couldn't create file from template.
But the file is created. Anyway I can't open the file. When clicking on it it gets downloaded and I can open it with my desktop office software. So the file itselfe is ok.

Should it be possible to use the CODE server by simply changing the kernels architecture or do I have to upgrade the whole system to 64bit? I would like to know if it should be possible to open/edit files with this workaround or if I have to upgrade the whole file system before worrying about this issue.
