### ISSUE TITLE
Use 'upload_tmp_dir' when available for PID and LOCK files

### ISSUE THREAD

**Issue by acsfer** [CollaboraOnline/richdocumentscode#132]
On a server with multiple PHP pools, only one CODE can be runing, because PID and LOCK files get the Owner and Group of the Pools. We faced a race condition where PID was owned by one user, and lock owned by another user, with PHP logging things like:

`WARNING: [pool sics] child 3371988 said into stderr: "Access to file denied: /tmp/loolwsd.pid"`

Something like this could help, instead of hard coding values like `/tmp`.
https://github.com/CollaboraOnline/richdocumentscode/blob/174259d4f7fe25a6881393de865da9b043e27679/proxy.php#L48

```
$tmp_dir = ini_get('upload_tmp_dir') ? ini_get('upload_tmp_dir') : sys_get_temp_dir();
```

and then use `$tmp_dir` to create those files, assuming each pool has it's own `upload_tmp_dir` set (which is a good practice), otherwise, fallback to system temp dir (and blame the sysadmin).

**Comment by timar** [comment]
@acsfer: Thank you for your suggestion!

**Comment by timar** [comment]
Relocating /tmp/loolwsd.pid is tricky, because it's created by the AppImage, we just read it from proxy.php. The usage of pidfile was initially a workaround, that in snap we could not use the pidof command.
