### ISSUE TITLE
Can't download pdf version

### ISSUE THREAD

**Issue by Thatoo** [CollaboraOnline/richdocumentscode#133]
Hello,

We have Nextcloud 21.0.1 and the laste version of CODE installed behind a reverse proxy nginx with the "2. SSL terminates at the proxy:" file from https://www.collaboraoffice.com/code/nginx-reverse-proxy/ .

It is working pretty well but we can't download pdf version from "file/download/pdf" . We can download all other format but pdf. If I check in the log file, I can found this kind of error every time I try to download a pdf :

> [ websrv_poll ] ERR  Download file [/opt/lool/child-roots/77Eog0oZ8r67Mntj/tmp/user/docs/iqimcpExcN6WxyC30X53WCFeceoXN24QBnZ6725LAQrEKzztqmXOtXGY8EXdc4W9/NAMEOFMYFILE.pdf] not found.| wsd/LOOLWSD.cpp:3243

Also, I was wondering if ti is possible to save as pdf (or export as pdf) within nextcloud? I don't need to download in my computer...

**Comment by fluboi** [comment]
Hi
It's no going to help, but we are facing the exact same issue. 
Also using an nginx reverse proxy as front. CODE is installed in an LXC container.

**Comment by kingul** [comment]
Not working here also, using Apache2 with NextCloud 22

**Comment by Thatoo** [comment]
I have installed Collabora Online with the same settings on a VM in Proxmox instead of an unprivileged CT and it does work perfectly!
So I guess the problem does come from proxmox unprivileged CT...

**Comment by Thatoo** [comment]
The solution was not "nesting=1" but "mknod=1"

I did add 
`features: mknod=1`
into the file /etc/pve/lxc/xxx.conf corresponding to the proxmox CT into proxmox host and I rebooted the CT and now I can download as PDF and print.
Thank you @fabian from Proxmox forum : https://forum.proxmox.com/threads/collabora-online-development-edition-in-unprivileged-ct-of-proxmox.93882/

**Comment by kingul** [comment]
@Thatoo Well, You didn't have to close this issue, because it's not fixed in anyway for me. 
We have native CODE installed, without containers. mknod is specified in my loolwsd.service file and pdf downloading is not working.

**Comment by Thatoo** [comment]
@kingul as You know because you already posted on it, this is a duplicate of https://github.com/CollaboraOnline/online/issues/2041 . So to centralised searches, problemes and solutiond, I closed this thread I created before discovering an other was existing.
I have discovered since that online code and issues are more reviewed than richdocument so you'll have more people interacting there than here. As you can read, in this thread I'm alone, no dev have come answering me neither adding tag or anything. 
You say you have native CODE so the other thread will be the good place. If you want me to apologize, it's not about closing but about opening this issue... Good day.
