### ISSUE TITLE
Please, add compatibility with NC22

### ISSUE THREAD

**Issue by elpraga** [CollaboraOnline/richdocumentscode#134]

**Comment by gcommit** [comment]
+1 Please add it

**Comment by MRFU510N88** [comment]
+1 in dire need of this

**Comment by jman0815** [comment]
+1 Please add it, i need this!

**Comment by MRFU510N88** [comment]
Is this in the pipelines?

**Comment by mrkara** [comment]
Should be resolved with the next minor release/build.

**Comment by gcommit** [comment]
When will it be released?

**Comment by bb** [comment]
@gcommit it was already released before you asked: https://github.com/CollaboraOnline/richdocumentscode/releases/tag/6.4.1004
