### ISSUE TITLE
Very high CPU usage when using emojis

### ISSUE THREAD

**Issue by Fuzzillogic** [CollaboraOnline/richdocumentscode#137]
Using emojis like 😋 in a text document leads to very high cpu usage, and depending on available resources, perhaps even denial of service. I'm running CODE server 6.4.1004 on Nextcloud 21.0.4, on a old AMD E-450 (x64) powered nettop with 8GiB, running Kubuntu 20.04.3. While overall performance on this machine is nothing to brag about (understatement, even RaspberryPi's are much faster these days) it is still workable, until even a single emoji is used. And while further testing right now, it even takes down the entire nextcloud instance; I had to restart the apache2 service...

It looks like an [upstream bug in LO](https://bugs.documentfoundation.org/show_bug.cgi?id=133249), and I see somewhat same issue on my much faster desktop. But according to some comments it might be Linux-only, and therefor especially relevant for CODE server.

STR:

1. Open a document in Collabora Online on a Nextcloud instance.
2. Enter some emojis

Expected: no significant CPU usage due to emojis
Actual: 100% usage (single core) for kitbroker/loolforkit process, for several seconds - if you are lucky.

**Comment by joshtrichards** [comment]
Not much can be done about this here. This would be an upstream matter - LO or maybe CO.

**Comment by Fuzzillogic** [comment]
Thanks for the update. I just re-tested the issue, and it seems to have been solved somehow in the mean time. Now on CODE server 23.5.503 (and recently on a faster machine) the problem is gone. Also on desktop with LO 7.6.2.1 the problem is gone. On both machines there is no increase in CPU usage anymore.
