### ISSUE TITLE
Sidebar buttons for NC and Collabora overlap

### ISSUE THREAD

**Issue by brtptrs** [CollaboraOnline/richdocumentscode#153]
Testing Collabora 21.11.0.3 on NC 23.0.0 RC3 it is not possible to klick on the sidebar button since it is overlapped by the NC-sidebar button.
![grafik](https://user-images.githubusercontent.com/8102905/143452201-0e6a9aab-1b0c-48d3-bead-ed9832cf5bf7.png)
Ubuntu 20.04
Firefox 94.0

**Comment by juliushaertl** [comment]
This is fixed with the final release of richdocuments 5.0.0 / Nextcloud 23.

**Comment by Ezinnem** [comment]
This icons overlap has been fixed.
