### ISSUE TITLE
Please, add compatibility with NC23

### ISSUE THREAD

**Issue by Brakelmann** [CollaboraOnline/richdocumentscode#154]

**Comment by leonardohlee** [comment]
please...

**Comment by w202mg** [comment]
Must be! Now also OnlyOffice is not working in NC! Had to rall back NC to 22 and keep using OnlyOffice.

**Comment by Wikinaut** [comment]
![grafik](https://user-images.githubusercontent.com/1151915/145583482-db65a4ff-2507-4515-a20a-c4374fdfeb4a.png)
![grafik](https://user-images.githubusercontent.com/1151915/145583612-36869f11-6294-44be-98a1-9c37c7407308.png)
![grafik](https://user-images.githubusercontent.com/1151915/145583663-ec43d0d6-e509-4796-9d71-5937387ecc1b.png)

Does not work for me. I cannot see any relevant error message.

**Comment by webermax** [comment]
Exactly same here - CODE stopped working right after upgrading to NC 23.

No logs on Ubuntu 20 or built in NC logs viewer.

Browser console does not give any hint neither.

**Comment by rototom** [comment]
same here. Are there any official comments on this?

**Comment by webermax** [comment]
...it's definetively the "Client App" 5.0 which is suboptimal when relying on the "stable" release channel (...).
Downgrading the client app to 4.x works for the moment.

[On the other hand upgrading the collabora docker container also broke things - using the sipped built-in app for now]

**Comment by Wikinaut** [comment]
When will this be fixed?

**Comment by leonardohlee** [comment]
> When will this be fixed?

I saw an update released today. but not fix NC23 issue

**Comment by legalbit** [comment]
Same here with CODE Srv 21.11.4. After downgrading the *Collabora Online App* from 5.0.0 to 4.2.3 manually it works as expected.

**Comment by Wikinaut** [comment]
Does not work in Collabora Online Version 21.11.6, released today (NC 23).

**Comment by Wikinaut** [comment]
I found that downgrading https://github.com/CollaboraOnline/richdocumentscode to 4.2.3 fixes this issue.
https://github.com/nextcloud-releases/richdocuments/releases/download/v4.2.3/richdocuments.tar.gz

**Comment by Wikinaut** [comment]
Reason is here: https://github.com/nextcloud/richdocuments/issues/1886

**Comment by gitgt** [comment]
I guess this should be closed.
