### ISSUE TITLE
Message: No content in reply from coolwsd. Is SSL enabled in error ?

### ISSUE THREAD

**Issue by hexitnz** [CollaboraOnline/richdocumentscode#156]
I get this error on the server logs when using Collabora in built code server.  Can anyone point me to where to control coolwsd and enabling/disabling SSL?

Ubuntu 20.04 64 / 6GB RAM
Nextcloud 23.0.0
Collabora Online - Built-in CODE Server	21.11.4
Collabora Online	4.1.2

Error: [STDERR] richdocumentscode (proxy.php) error exit, PID: xxxx, Message: No content in reply from coolwsd. Is SSL enabled in error ?

**Comment by zynexiz** [comment]
Depending on your setup, it could be different issues. I just found why mine didn't work, you MUST have TSLv1.2 enabled in NextCloud VirtualHost part to make it work (at lest for Apache and reverse proxy setup). I just used TLSv1.3, which made it break.

**Comment by Ezinnem** [comment]
We can safely close this issue.

Enabling TLS 1.2 and then restarting Apache handles the error.
