### ISSUE TITLE
[Regression] Missing icons in NC 23

### ISSUE THREAD

**Issue by Wikinaut** [CollaboraOnline/richdocumentscode#159]
# NC 22 (ok)
![grafik](https://user-images.githubusercontent.com/1151915/146528726-70a08744-fafc-490a-a07b-6f9a56492fcd.png)

# NC 23: not okay: icons are missing
![grafik](https://user-images.githubusercontent.com/1151915/146528834-9b425490-b6c9-4504-b9c1-37305b06a1ad.png)

**Comment by Wikinaut** [comment]
Does not work in Version 21.11.6.

**Comment by Wikinaut** [comment]
Related to https://github.com/nextcloud/richdocuments/issues/1886

**Comment by Wikinaut** [comment]
When will this be fixed?

**Comment by shashank-brdj** [comment]
Same issue here, any fix or workaround yet?

**Comment by timur-g** [comment]
This is a tracker for Built-In CODE, so IDK why missing icons are here, that should be NC feature. 
I see icons in my NC 7.1.5.
I close. If you can explain differently, please do.
