### ISSUE TITLE
Cant copy resultant data from cell using formula

### ISSUE THREAD

**Issue by joshbowyer** [CollaboraOnline/richdocumentscode#164]
If I make a cell which populates data with a formula, there is no way for me to copy the cell contents as displayed. It only copies the source which would be the formula.

**Comment by Ezinnem** [comment]
This is similar to https://github.com/CollaboraOnline/online/issues/4206

**Comment by thebearon** [comment]
Yes, let's track this in https://github.com/CollaboraOnline/online/issues/4206 .

**Comment by mitohund** [comment]
I am the one who opened #4206 and only now noticed this issue here. Unfortunately, there does not seem to be any interest in this problem. Any suggestions on how to get people to care?
