### ISSUE TITLE
cant open xls or ods files

### ISSUE THREAD

**Issue by thomaselsaesser** [CollaboraOnline/richdocumentscode#166]
I have NC 23 and latest richdocumentscode 21.11.103
OpenOffice and Word documents open fine. If i would open xls or ods files no error message or any. if i load a new xls or ods file up to nextcloud , i can open also this files . But not also existing files in nextcloud.

Any idea?

Regars
Thomas

**Comment by Ezinnem** [comment]
This issue does not seem reproducible on my end using CODE Server 21.11.402 on Nextcloud 23.0.3.

@thomaselsaesser, please can you test again using the updated version?
