### ISSUE TITLE
CODE ARM 64 stopped working after upgrade to Nextcloud Hub II (23.0.3)

### ISSUE THREAD

**Issue by JazMTaz** [CollaboraOnline/richdocumentscode#173]
CODE ARM 64 stopped working after upgrade to Nextcloud Hub II (23.0.3). I can get it to work by going to the '[Settings > Administration > Collabora Online]' and changing to 'Use your own server', or 'Use a demo server' and then changing it back, but if I restart then I must repeat the process to get it working again.

Running on bare-metal host, not in docker or other virtual image.

Operating System: | Linux 5.4.0-1056-raspi aarch64
8GB RAM

PHP 7.4.28
mysql (MariaDB) 10.5.15
nginx version: nginx/1.18.0 (Ubuntu)

Logging errors:

GET /nextcloud/core/preview?fileId=1950452&c=7446408ca71c10ccbcef7726946668ad&x=250&y=250&forceIcon=0&a=0
from by[LAN IP] by [NC user] at 2022-03-23T03:13:16+00:00

[no app in context] Info: Deprecated event type for OCA\Files::loadAdditionalScripts: Symfony\Component\EventDispatcher\GenericEvent is used

GET /nextcloud/apps/files/
from by[LAN IP] by [NC user] at 2022-03-23T03:13:07+00:00

**Comment by gitgt** [comment]
Issue 172 says that updating apps solves the issue so I close this one.
