### ISSUE TITLE
Doesn't work with a non-default port

### ISSUE THREAD

**Issue by juliushaertl** [CollaboraOnline/richdocumentscode#18]
The app seems to have issues with Nextcloud running on a port that is not 80/443. 

It might be already enough to use `$_SERVER['HTTP_HOST']` instead of the SERVER_NAME in https://github.com/CollaboraOnline/richdocumentscode/blob/965b80251c10effa3901395666ebf648b22c4ad7/proxy.php#L245 but I could not test that yet.

**Comment by timar** [comment]
I tested this, and HTTP_HOST instead of SERVER_NAME worked well, when Nextcloud was running on port 9433 (https),
