### ISSUE TITLE
Nextcloud logo is missing from top left corner

### ISSUE THREAD

**Issue by timar** [CollaboraOnline/richdocumentscode#182]
version 21.11.402:
![image](https://user-images.githubusercontent.com/290614/166898783-b1a0b815-07ca-473a-86c1-55fa8475228d.png)

**Comment by AaronADev** [comment]
Verified facing same issue in NC 24. Also, in some instances the icons for the editor bar do not load. I assume it would be related.

**Comment by Anarch157a** [comment]
> Verified facing same issue in NC 24. Also, in some instances the icons for the editor bar do not load. I assume it would be related.

I noticed that the icons do not load when using Breeze Dark Theme.

**Comment by Ezinnem** [comment]
Fixed with [ #5661](https://github.com/CollaboraOnline/online/pull/5661)
