### ISSUE TITLE
22.5.301 table calculation Nextcloud Android app or mobile browser can't be editing 

### ISSUE THREAD

**Issue by mr-bolle** [CollaboraOnline/richdocumentscode#189]
Hi,

Since the last update I'm not able to edit any (existing or new) table calculation files.

After installing the collaboration in code server, i can't edit any files. The values are visible in the cell field, however the cell is still empty.

With the desktop browser i can still edit the files.

Nextcloud Server: 23.0.6 - Docker Image x64
Nextcloud Android App: 3.20.3

Reinstall the server doesn't help. 

![Screenshot_20220702-082026_Nextcloud.jpg](https://user-images.githubusercontent.com/22414212/176989488-750124a4-b754-4b95-b487-c4a3ed42b5c2.jpg)

![Screenshot_20220702-082104_Nextcloud.jpg](https://user-images.githubusercontent.com/22414212/176989495-2f125c1e-654e-4b93-b533-a2a2cd1c2d08.jpg)

**Comment by jakobroehrl** [comment]
I have exactly the same problem. 
I only can insert/change data if I double tip in the cell directly.

**Comment by mr-bolle** [comment]
This issue is gone with version 22.5.502

**Comment by mr-bolle** [comment]
This issue is gone with Version 22.5.502

**Comment by D1reW0lf** [comment]
> This issue is gone with Version 22.5.502

Hello.

I have 22.5.502 and it still happens on iPad.
Basically the lower left edit icon is still missing.

Thank you.
