### ISSUE TITLE
Proxy fails with local collabora already running

### ISSUE THREAD

**Issue by juliushaertl** [CollaboraOnline/richdocumentscode#19]
When a real collabora installation is already present on the same host (with SSL enabled) the proxy fails to connect to that one. It seems that the proxy.php currently only supports http to connect to loolwsd and therefore the local fallback is not working. I'd suggest to either figure out a way to connect via SSL in such a case or at least properly warn the user about issues with that.

**Comment by timar** [comment]
Addressed with PR #21
