### ISSUE TITLE
 Collabora Online - Built-in CODE Server - does not load cvs files

### ISSUE THREAD

**Issue by tobefrank1** [CollaboraOnline/richdocumentscode#190]
Hello. 

The Collabora Online - Built-in CODE Server V22.5.301 - on Nextcloud 24.0.0 does not load cvs files.
Loading never ends. Other files like xlsm work fine out of the box. 
 
The Collabora Demo-Server does not have any problems loading cvs files.   

I thought you should know. 

Keep up your great work.

**Comment by gitgt** [comment]
I see the same with NC 25 and CODE 22.5.8. Guess it cannot show import dialog.

**Comment by joshtrichards** [comment]
Works for me in v23.5.503 (v23.05.5.3) + NC Office v8.2.2

Can you both retest with a newer version and report back?

**Comment by timur-g** [comment]
Also works for me in v23.5.503
