### ISSUE TITLE
Can't install "Collabora Online - Built-in CODE Server" : architecture

### ISSUE THREAD

**Issue by alexander-rebello** [CollaboraOnline/richdocumentscode#198]
Hello, I'm having issues with installing Collabora Online - Built-in CODE Server. When I try to do so, I always get this message:

`App "Collabora Online - Built-in CODE Server" cannot be installed because the following dependencies are not fulfilled: The following architectures are supported: x86_64`

I can assure, that my hoster is using x86_64 architecture, but Nextcloud won't recognize it. Nextcloud doesn't even know what processor the server has, because in settings>system it says unknown processor. Anyway to force install it or just tell Nextcloud what architecture it has? Also I saw that inn other cases the problem was the os, but I am using Linux. Thanks for any help :)

**Comment by smCloudInTheSky** [comment]
Hi, 
Same problem. 
Here are some infos : 
Operating system: FreeBSD 12.2-RELEASE-p14 FreeBSD 12.2-RELEASE-p14 325282c09a5(HEAD) TRUENAS amd64

Webserver: nginx/1.20.2 (fpm-fcgi)

Database: mysql 8.0.28

PHP version: 7.4.27

Modules loaded: Core, date, libxml, pcre, hash, Reflection, SPL, session, standard, cgi-fcgi, mysqlnd, apcu, bcmath, bz2, ctype, curl, dom, mbstring, fileinfo, filter, gd, gmp, iconv, imagick, intl, json, ldap, exif, openssl, pcntl, PDO, posix, SimpleXML, xml, xmlwriter, zip, zlib, pdo_mysql, redis, xmlreader, xsl, Zend OPcache

Nextcloud version: 24.0.4 - 24.0.4.1

Updated from an older Nextcloud/ownCloud or fresh install:

Where did you install Nextcloud from: unknown

<details><summary>Signing status</summary>

Array ( )

</details>

<details><summary>List of activated apps</summary>

Enabled:
 - accessibility: 1.10.0
 - admin_audit: 1.14.0
 - audioplayer: 3.3.0
 - breezedark: 24.0.2
 - bruteforcesettings: 2.4.0
 - calendar: 3.4.3
 - camerarawpreviews: 0.8.0
 - circles: 24.0.1
 - cloud_federation_api: 1.7.0
 - comments: 1.14.0
 - contacts: 4.2.0
 - contactsinteraction: 1.5.0
 - dashboard: 7.4.0
 - dav: 1.22.0
 - deck: 1.7.1
 - duplicatefinder: 0.0.15
 - federatedfilesharing: 1.14.0
 - files: 1.19.0
 - files_downloadactivity: 1.13.0
 - files_external: 1.16.1
 - files_pdfviewer: 2.5.0
 - files_rightclick: 1.3.0
 - files_sharing: 1.16.2
 - files_trashbin: 1.14.0
 - files_versions: 1.17.0
 - files_videoplayer: 1.13.0
 - firstrunwizard: 2.13.0
 - forms: 2.5.1
 - group_default_quota: 0.1.4
 - groupfolders: 12.0.1
 - logreader: 2.9.0
 - lookup_server_connector: 1.12.0
 - news: 18.1.1
 - nextcloud_announcements: 1.13.0
 - notifications: 2.12.0
 - oauth2: 1.12.0
 - password_policy: 1.14.0
 - photos: 1.6.0
 - privacy: 1.8.0
 - provisioning_api: 1.14.0
 - quota_warning: 1.14.0
 - recommendations: 1.3.0
 - serverinfo: 1.14.0
 - settings: 1.6.0
 - sharebymail: 1.14.0
 - support: 1.7.0
 - survey_client: 1.12.0
 - systemtags: 1.14.0
 - text: 3.5.1
 - theming: 1.15.0
 - twofactor_backupcodes: 1.13.0
 - updatenotification: 1.14.0
 - user_status: 1.4.0
 - user_usage_report: 1.8.0
 - viewer: 1.8.0
 - weather_status: 1.4.0
 - workflow_script: 1.9.0
 - workflowengine: 2.6.0
Disabled:
 - activity: 2.15.0
 - audioplayer_sonos: 1.3.0
 - encryption: 2.10.0
 - federation: 1.11.0
 - files_trackdownloads: 1.11.0
 - richdocumentscode
 - user_ldap



</details>

<details><summary>Configuration (config/config.php)</summary>

{
    "apps_paths": [
        {
            "path": "\/usr\/local\/www\/nextcloud\/apps",
            "url": "\/apps",
            "writable": true
        },
        {
            "path": "\/usr\/local\/www\/nextcloud\/apps-pkg",
            "url": "\/apps-pkg",
            "writable": true
        }
    ],
    "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
    "dbtype": "mysql",
    "version": "24.0.4.1",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "installed": true,
    "mail_smtpmode": "smtp",
    "mail_sendmailmode": "pipe",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpport": "465",
    "mail_smtpsecure": "ssl",
    "mail_smtpauth": 1,
    "maintenance": false,
    "theme": "",
    "loglevel": 0,
    "one-click-instance": true,
    "one-click-instance.user-limit": 100,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "memcache.distributed": "\\OC\\Memcache\\Redis",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "updater.release.channel": "stable",
}


</details>

Cron Configuration: Array ( [backgroundjobs_mode] => cron [lastcron] => 1661674211 )

External storages: yes

<details><summary>External storage configuration</summary>

No mounts configured


</details>

Encryption: no

User-backends:

OC\User\Database

Browser: Mozilla/5.0 (X11; Linux x86_64; rv:104.0) Gecko/20100101 Firefox/104.0

**Comment by Phozer** [comment]
Same Issue here. 😥

```
Exception: App "Collabora Online - Built-in CODE Server" cannot be installed because the following dependencies are not fulfilled: The following architectures are supported: x86_64
/home/vifaweze/www/cloud.domain/nextcloud/lib/private/Installer.php - line 141:

OC_App::checkAppDependencies(OC\AllConfig {}, OC\L10N\LazyL10N {}, [ "richdocum ... "], false)

/home/vifaweze/www/cloud.domain/nextcloud/apps/settings/lib/Controller/AppSettingsController.php - line 451:

OC\Installer->installApp("richdocumentscode")

/home/vifaweze/www/cloud.domain/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 225:

OCA\Settings\Controller\AppSettingsController->enableApps([ "richdocumentscode"], [])

/home/vifaweze/www/cloud.domain/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 133:

OC\AppFramework\Http\Dispatcher->executeController(OCA\Settings ... {}, "enableApps")

/home/vifaweze/www/cloud.domain/nextcloud/lib/private/AppFramework/App.php - line 172:

OC\AppFramework\Http\Dispatcher->dispatch(OCA\Settings ... {}, "enableApps")

/home/vifaweze/www/cloud.domain/nextcloud/lib/private/Route/Router.php - line 298:

OC\AppFramework\App::main("OCA\\Settin ... r", "enableApps", OC\AppFramew ... {}, [ "settings. ... "])

/home/vifaweze/www/cloud.domain/nextcloud/lib/base.php - line 1023:

OC\Route\Router->match("/settings/apps/enable")

/home/vifaweze/www/cloud.domain/nextcloud/index.php - line 36:

OC::handleRequest()
```

Let me know if more Information is required. I will try to provide what i can.

**Comment by mika-data** [comment]
"Collabora Online - Built-in CODE Server" App cannot be installed. Error message is very general:
"Es ist ein Fehler bei der Anfrage aufgetreten. Es kann nicht fortgefahren werden."
https://cloud.XXXXX/index.php/settings/apps/app-bundles/richdocumentscode#app-content

**Comment by gitgt** [comment]
If NextCloud doesn't recognize architecture, please explain why you report it for Built-in CODE? 
Did you report it to Nextcloud?

**Comment by alexander-rebello** [comment]
Well, I wanted to know from you, if there is a way to "force install" it, so it doesn't check for the architecture

**Comment by skyynet** [comment]
Tried to install on FreeBSD 64bit today and got the same error message. Would be nice, if someone could check the architecture identification code, so FreeBSD users could use it, too.

App "Collabora Online - Built-in CODE Server" cannot be installed because the following dependencies are not fulfilled: The following architectures are supported: x86_64 

Also tried the ARM64 version, which failed to install, too.

App "Collabora Online - Built-in CODE Server (ARM64)" cannot be installed because the following dependencies are not fulfilled: The following architectures are supported: aarch64

**Comment by joshtrichards** [comment]
https://github.com/CollaboraOnline/richdocumentscode#system-requirements

The check is accurate, if a bit vague. It does not support FreeBSD.

**Comment by timur-g** [comment]
Let us close as WontFix.

**Comment by joshtrichards** [comment]
> I can assure, that my hoster is using x86_64 architecture, but Nextcloud won't recognize it. Nextcloud doesn't even know what processor the server has, because in settings>system it says unknown processor. Anyway to force install it or just tell Nextcloud what architecture it has? Also I saw that inn other cases the problem was the os, but I am using Linux. Thanks for any help :)

@alexander-rebello: The dependency check you're hitting up against is in Nextcloud Server here:

https://github.com/nextcloud/server/blob/5d05da0f8da263945a0bb118167b4c9d115b36b2/lib/private/App/Platform.php#L84

It's just a call to `php_uname()`:

https://www.php.net/manual/en/function.php-uname.php

It sounds like either it really isn't Linux or that that function isn't working on your web host.
