### ISSUE TITLE
Make app compatible with NC v25

### ISSUE THREAD

**Issue by rakekniven** [CollaboraOnline/richdocumentscode#200]
Today NC25 is out and this app needs some love ❤️ .

**Comment by Grizzly-ger** [comment]
on my home instance it seems to work. No errors in the log. Editing possible.  But I'm also wating with the upgrad of my other instance till it's official updated for Hub 3

**Comment by jabo59** [comment]
Did the upgrade today from NC24 to NC25. Since then opening of documents is failing. Instead of opening in CODE the document is downloaded. When I switch to a CODE demo server it works as expected. Seems there is an error with the builtin CODE.

**Comment by jabo59** [comment]
Sorry.

**Comment by timar** [comment]
maxversion was bumped in  #201
