### ISSUE TITLE
Non English characters in comments (using richdocumentscode)

### ISSUE THREAD

**Issue by pr3thib** [CollaboraOnline/richdocumentscode#203]
Using the **Insert -> Comment** command, the comment is not saved if it contains non English characters.
Don't know if it's a new issue, I have just observed it on the current richdocumentscode 22.5.702.

Two points worth mentioning:

- If the comment is created off line (using LibreOffice) all characters are accepted and saved. If I further upload the document to Nextcloud, comments are displayed all right (but can only modified if all non English characters are removed).
- If I use a demo server (*) instead of the server's own, all is fine. Switching back to the server's own code results in same as if the document had been uploaded as in point above. i.e. comments are displayed all right (but can only modified if all non English characters are removed).

(*) I have tried different demo servers and they all work fine.
__
Pierre Thibaudeau

**Comment by vsandre** [comment]
I can confirm this. In my case the problem is the non-ascii character in my username.
One suggested location of the problem could be the proxy.php 

https://github.com/CollaboraOnline/online/issues/4732

**Comment by gitgt** [comment]
Also here https://github.com/CollaboraOnline/online/issues/4732 .
