### ISSUE TITLE
After every server reboot: Documents do not open, download is offerd

### ISSUE THREAD

**Issue by jakobroehrl** [CollaboraOnline/richdocumentscode#206]
I can work with office without any problems till I reboot the server.
Then Documents do not open, a download is offered.
To solve this I must click here:
![image](https://user-images.githubusercontent.com/24530680/202378149-caacbcb7-45dc-4033-865f-f628ff36f377.png)
and when it says:
![image](https://user-images.githubusercontent.com/24530680/202378201-1e481891-18b6-4851-a21e-453049581e2d.png)
Offices works again

---
Collabora Online - Built-in CODE Server 22.5.802

**Comment by Moxified** [comment]
I have the same issue.

**Comment by kvetal** [comment]
And me have the same issue.

**Comment by jakobroehrl** [comment]
I found out, it's the restart of the php service that triggers the problem.

**Comment by ernolf** [comment]
I have had the same issue but... not allways

I solved it for me with this dirty but effective workaround:

Create this file `/etc/systemd/system/richdocuments.service`

    [Unit]
    Description = richdocuments activate-config
    After=network.target
    
    [Service]
    ExecStart=/usr/bin/php -f /var/www/nextcloud/occ richdocuments:activate-config
    User=www-data
    Group=www-data
    
    [Install]
    WantedBy = multi-user.target

enable with `sudo systemctl enable --now richdocuments.service`

Do not forget to remove this workaround after this issue is solved by the package maintainers:

`sudo systemctl disable richdocuments.service && sudo rm /etc/systemd/system/richdocuments.service`

I hope this helps.

**Comment by rursache** [comment]
having the same issue using the [linuxserver/nextcloud](https://hub.docker.com/r/linuxserver/nextcloud) container

**Comment by Moxified** [comment]
I found that the workaround service wasn't reliably working for me.  I changed the dependency to:

After=apache2.service

This has worked better for my build.  FWIW.

**Comment by jakobroehrl** [comment]
On my systems it's not occurring any more

**Comment by safranat** [comment]
I have the same problem with the nextcloud 25 snap on ubuntu server 22.04.  It is possible to create new collabora documents from the existing templates but it will not open any new or existing documents.
If I install the same snap on ubuntu desktop 22.04 it works. I would like to know what collabora needs from ubuntu which the desktop version 22.04 provides and the server 22.04 does not.
