### ISSUE TITLE
Failed to connect to localhost port 80 error

### ISSUE THREAD

**Issue by CarlBishop** [CollaboraOnline/richdocumentscode#210]
Dears all.

I have the following error every 5 minutes since latest update.
I don't know where and what to check.

It runs under nextcloud 25.0.3 and hestiacp (latest)

Can someone point me in the right direction to fix this?

Thank you

```
[richdocuments] Errore: GuzzleHttp\Exception\ConnectException: cURL error 7: Failed to connect to localhost port 80: Connection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://localhost/apps/richdocumentscode/proxy.php?req=/hosting/capabilities at <<closure>>

 0. /home/xxxxuser/web/office.XXX.com/public_html/3rdparty/guzzlehttp/guzzle/src/Handler/CurlFactory.php line 158
    GuzzleHttp\Handler\CurlFactory::createRejection()
 1. /home/xxxxuser/web/office.XXX.com/public_html/3rdparty/guzzlehttp/guzzle/src/Handler/CurlFactory.php line 110
    GuzzleHttp\Handler\CurlFactory::finishError()
 2. /home/xxxxuser/web/office.XXX.com/public_html/3rdparty/guzzlehttp/guzzle/src/Handler/CurlHandler.php line 47
    GuzzleHttp\Handler\CurlFactory::finish()
 3. /home/xxxxuser/web/office.XXX.com/public_html/lib/private/Http/Client/DnsPinMiddleware.php line 113
    GuzzleHttp\Handler\CurlHandler->__invoke()
 4. /home/xxxxuser/web/office.XXX.com/public_html/3rdparty/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php line 35
    OC\Http\Client\DnsPinMiddleware->OC\Http\Client\{closure}("*** sensitive parameters replaced ***")
 5. /home/xxxxuser/web/office.XXX.com/public_html/3rdparty/guzzlehttp/guzzle/src/Middleware.php line 31
    GuzzleHttp\PrepareBodyMiddleware->__invoke()
 6. /home/xxxxuser/web/office.XXX.com/public_html/3rdparty/guzzlehttp/guzzle/src/RedirectMiddleware.php line 71
    GuzzleHttp\Middleware::GuzzleHttp\{closure}("*** sensitive parameters replaced ***")
 7. /home/xxxxuser/web/office.XXX.com/public_html/3rdparty/guzzlehttp/guzzle/src/Middleware.php line 63
    GuzzleHttp\RedirectMiddleware->__invoke()
 8. /home/xxxxuser/web/office.XXX.com/public_html/3rdparty/guzzlehttp/guzzle/src/HandlerStack.php line 75
    GuzzleHttp\Middleware::GuzzleHttp\{closure}("*** sensitive parameters replaced ***")
 9. /home/xxxxuser/web/office.XXX.com/public_html/3rdparty/guzzlehttp/guzzle/src/Client.php line 331
    GuzzleHttp\HandlerStack->__invoke()
10. /home/xxxxuser/web/office.XXX.com/public_html/3rdparty/guzzlehttp/guzzle/src/Client.php line 168
    GuzzleHttp\Client->transfer()
11. /home/xxxxuser/web/office.XXX.com/public_html/3rdparty/guzzlehttp/guzzle/src/Client.php line 187
    GuzzleHttp\Client->requestAsync()
12. /home/xxxxuser/web/office.XXX.com/public_html/lib/private/Http/Client/Client.php line 218
    GuzzleHttp\Client->request()
13. /home/xxxxuser/web/office.XXX.com/public_html/apps/richdocuments/lib/Service/CapabilitiesService.php line 136
    OC\Http\Client\Client->get()
14. /home/xxxxuser/web/office.XXX.com/public_html/apps/richdocuments/lib/Service/CapabilitiesService.php line 74
    OCA\Richdocuments\Service\CapabilitiesService->refetch()
15. /home/xxxxuser/web/office.XXX.com/public_html/apps/richdocuments/lib/AppInfo/Application.php line 80
    OCA\Richdocuments\Service\CapabilitiesService->getCapabilities()
16. /home/xxxxuser/web/office.XXX.com/public_html/lib/private/AppFramework/Bootstrap/FunctionInjector.php line 67
    OCA\Richdocuments\AppInfo\Application->OCA\Richdocuments\AppInfo\{closure}("*** sensitive parameters replaced ***")
17. /home/xxxxuser/web/office.XXX.com/public_html/lib/private/AppFramework/Bootstrap/BootContext.php line 51
    OC\AppFramework\Bootstrap\FunctionInjector->injectFn()
18. /home/xxxxuser/web/office.XXX.com/public_html/apps/richdocuments/lib/AppInfo/Application.php line 135
    OC\AppFramework\Bootstrap\BootContext->injectFn()
19. /home/xxxxuser/web/office.XXX.com/public_html/lib/private/AppFramework/Bootstrap/Coordinator.php line 190
    OCA\Richdocuments\AppInfo\Application->boot()
20. /home/xxxxuser/web/office.XXX.com/public_html/lib/private/legacy/OC_App.php line 208
    OC\AppFramework\Bootstrap\Coordinator->bootApp()
21. /home/xxxxuser/web/office.XXX.com/public_html/lib/private/legacy/OC_App.php line 141
    OC_App::loadApp()
22. /home/xxxxuser/web/office.XXX.com/public_html/lib/base.php line 1027
    OC_App::loadApps()
23. /home/xxxxuser/web/office.XXX.com/public_html/index.php line 36
    OC::handleRequest()

GET /apps/logreader/poll?lastReqId=JuyfThhgd0LqWmzYimII
```

**Comment by coop2540** [comment]
Hi! 
I've the same error.
Using Nextcloud 26, php8.0 on hestiacp with nginx

GuzzleHttp\Exception\ConnectException: cURL error 7: Failed to connect to localhost port 80: Connection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://localhost/apps/richdocumentscode/proxy.php?req=/hosting/capabilities

    /home/mysite/web/myurl/public_html/3rdparty/guzzlehttp/guzzle/src/Handler/CurlFactory.php - line 158:

    GuzzleHttp\Handler\CurlFactory::createRejection("*** sensiti ... *")

    /home/mysite/web/myurl/public_html/3rdparty/guzzlehttp/guzzle/src/Handler/CurlFactory.php - line 110:

    GuzzleHttp\Handler\CurlFactory::finishError()

    /home/mysite/web/myurl/public_html/3rdparty/guzzlehttp/guzzle/src/Handler/CurlHandler.php - line 47:

    GuzzleHttp\Handler\CurlFactory::finish()

    /home/mysite/web/myurl/public_html/lib/private/Http/Client/DnsPinMiddleware.php - line 114:

    GuzzleHttp\Handler\CurlHandler->__invoke()

    /home/mysite/web/myurl/public_html/3rdparty/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php - line 35:

    OC\Http\Client\DnsPinMiddleware->OC\Http\Client\{closure}("*** sensiti ... *")

    /home/mysite/web/myurl/public_html/3rdparty/guzzlehttp/guzzle/src/Middleware.php - line 31:

    GuzzleHttp\PrepareBodyMiddleware->__invoke()

    /home/mysite/web/myurl/public_html/3rdparty/guzzlehttp/guzzle/src/RedirectMiddleware.php - line 71:

    GuzzleHttp\Middleware::GuzzleHttp\{closure}("*** sensiti ... *")

    /home/mysite/web/myurl/public_html/3rdparty/guzzlehttp/guzzle/src/Middleware.php - line 63:

    GuzzleHttp\RedirectMiddleware->__invoke()

    /home/mysite/web/myurl/public_html/3rdparty/guzzlehttp/guzzle/src/HandlerStack.php - line 75:

    GuzzleHttp\Middleware::GuzzleHttp\{closure}("*** sensiti ... *")

    /home/mysite/web/myurl/public_html/3rdparty/guzzlehttp/guzzle/src/Client.php - line 331:

    GuzzleHttp\HandlerStack->__invoke()

    /home/mysite/web/myurl/public_html/3rdparty/guzzlehttp/guzzle/src/Client.php - line 168:

    GuzzleHttp\Client->transfer()

    /home/mysite/web/myurl/public_html/3rdparty/guzzlehttp/guzzle/src/Client.php - line 187:

    GuzzleHttp\Client->requestAsync("*** sensiti ... *")

    /home/mysite/web/myurl/public_html/lib/private/Http/Client/Client.php - line 226:

    GuzzleHttp\Client->request()

    /home/mysite/web/myurl/public_html/apps/richdocuments/lib/Service/CapabilitiesService.php - line 135:

    OC\Http\Client\Client->get()

    /home/mysite/web/myurl/public_html/apps/richdocuments/lib/AppInfo/Application.php - line 206:

    OCA\Richdocuments\Service\CapabilitiesService->refetch()

    /home/mysite/web/myurl/public_html/apps/richdocuments/lib/AppInfo/Application.php - line 138:

    OCA\Richdocuments\AppInfo\Application->checkAndEnableCODEServer()

    /home/mysite/web/myurl/public_html/lib/private/AppFramework/Bootstrap/Coordinator.php - line 200:

    OCA\Richdocuments\AppInfo\Application->boot()

    /home/mysite/web/myurl/public_html/lib/private/legacy/OC_App.php - line 213:

    OC\AppFramework\Bootstrap\Coordinator->bootApp()

    /home/mysite/web/myurl/public_html/lib/private/legacy/OC_App.php - line 141:

**Comment by CarlBishop** [comment]
Now on nextcloud 27 I have the same issue...

**Comment by joshtrichards** [comment]
Is the `richdocumentscode` app also installed and activated? Your logs only indicate `richdocuments` is installed.

What happens if you try to connect to `http://localhost/apps/richdocumentscode/proxy.php?req=/hosting/capabilities` from your host?

Also, what happens when you go to *Administration settings -> Office* and confirm your settings?

**Comment by CarlBishop** [comment]
> Is the `richdocumentscode` app also installed and activated? Your logs only indicate `richdocuments` is installed.


Of course
> 
> What happens if you try to connect to `http://localhost/apps/richdocumentscode/proxy.php?req=/hosting/capabilities` from your host?


![image](https://github.com/CollaboraOnline/richdocumentscode/assets/12203647/a3a85e47-3800-4fe8-ac9c-3699a01780d2)

> 
> Also, what happens when you go to _Administration settings -> Office_ and confirm your settings?


On first stage it gives error, if I refresh the page everything is green

By the way the office features are working, it is only matter of continuous logs

**Comment by CarlBishop** [comment]
I close this since it is opened more than one year
