### ISSUE TITLE
`no_glibc` in docker image nextcloud:25-fpm-alpine

### ISSUE THREAD

**Issue by maurerle** [CollaboraOnline/richdocumentscode#212]
Using the nextcloud docker image with alpine, this app is not installed properly, as the url:
`custom_apps/richdocumentscode/proxy.php?status`
shows `no_glibc`.

This is quite bad as there is no migration path or explaination to a glibc environment.

Just using `nextcloud:25-fpm` does not work.

Maybe this should be added in some docs or when installing the package

**Comment by maurerle** [comment]
in alpine, the www-data user is 82, while it is 33 in nextcloud:25-fpm.

Using something like:
`chown --from=82:82 33:33 -R /var/www/html`
`chown --from=82 33 -R /var/www/html`
works to migrate the permissions

after this, one can restart the docker-container and have working richdocuments.

Still I would like to see a little more documentation about this issue

**Comment by joshtrichards** [comment]
Hi @maurerle - Glad you got it worked out!

The docs say it requires glibc and won't work with musl (e.g. alpine):

https://github.com/CollaboraOnline/richdocumentscode#system-requirements

> This is quite bad as there is no migration path or explaination to a glibc environment.
> Still I would like to see a little more documentation about this issue

What do you have in mind?

**Comment by maurerle** [comment]
Thanks for getting back to this.
I would have liked a warning on this page (e.g. in the app selection on your nextcloud before installing)

And would like a pre install check if the system has musl, and fail the app install if not?

I remember it took me some time to find out what the reason was.
But maybe the alpine images aren't actually as popular as I think
