### ISSUE TITLE
Update to 22.05.12?

### ISSUE THREAD

**Issue by jakobroehrl** [CollaboraOnline/richdocumentscode#216]
When will there be an update to 22.05.12?
This would be awesome :)

**Comment by roever-rl** [comment]
I second this.
I was also wondering if that version adds support for the Pick Link function in nextcloud office? Really looking forward to test out the new AI features.

**Comment by gitgt** [comment]
12.05.12.4 is ready .

**Comment by jakobroehrl** [comment]
@gitgt Thanks a lot. 
What is to do, to build an release?
Currently its only tagged.

**Comment by jakobroehrl** [comment]
How to get an update here?
https://apps.nextcloud.com/apps/richdocumentscode

**Comment by jakobroehrl** [comment]
@juliushaertl How to get this update in here?
https://apps.nextcloud.com/apps/richdocumentscode

**Comment by juliushaertl** [comment]
Collabora is working on that, but there seem to be some issues with the app image build as far as I'm aware. I'll check back with them next week again during our regular meetings.
