### ISSUE TITLE
Typo in proxy.php

### ISSUE THREAD

**Issue by RealKoenisch** [CollaboraOnline/richdocumentscode#229]
Typo in line 85 proxy.php 

`    {
        $remoteFontConfig = "--o:remote_font_config.url=https://" . $_SERVER['HTTP_HOST'] . preg_replace("/richdocumentscode.*$/", "richdocuments/settings/fonts.json", _SERVER['REQUEST_URI']);
    }`

correct
`    {
        $remoteFontConfig = "--o:remote_font_config.url=https://" . $_SERVER['HTTP_HOST'] . preg_replace("/richdocumentscode.*$/", "richdocuments/settings/fonts.json", $_SERVER['REQUEST_URI']);
    }`

the $ is missing at the 2nd $_SERVER

**Comment by Scarat95** [comment]
> This might fix #226 🤔

Yep. Same issue as #226
After this fix it works again!

**Comment by JazMTaz** [comment]
Great catch, updated proxy.php line 85 and it is now fixed here as well, thanks.

**Comment by timar** [comment]
@RealKoenisch thanks!
