### ISSUE TITLE
App screenshot does not appear in Nextcloud 19

### ISSUE THREAD

**Issue by timar** [CollaboraOnline/richdocumentscode#23]
App screenshot does not appear in Nextcloud 19:
![image](https://user-images.githubusercontent.com/290614/83571230-b0fe8800-a527-11ea-88d0-335d631cef5f.png)

https://demo4.collaboraonline.com:9443/settings/apps/office

OTOH, 
- https://apps.nextcloud.com/?search=collabora
- https://apps.nextcloud.com/apps/richdocumentscode
are good...

**Comment by juliushaertl** [comment]
Most likely fixed once https://github.com/nextcloud/usercontent.apps.nextcloud.com/pull/6 is merged and the usercontent proxy has synced the screenshot

**Comment by juliushaertl** [comment]
@timar Seems to work now.

**Comment by timar** [comment]
> @timar Seems to work now.

Indeed. Thanks.
