### ISSUE TITLE
Webserver complains about a missing fonts.json file

### ISSUE THREAD

**Issue by monochromec** [CollaboraOnline/richdocumentscode#232]
When installing the CO built-in CODE server the following error message appears in the web server's logs:

```info AH00128: File does not exist: <path_to_NC>/apps/richdocuments/settings/fonts.json "COOLWSD HTTP Agent 23.05.1.3"```

Webserver is Apache 2.4 with SAPI module for PHP access. NC is 27.0.1 running on PHP 8.2.7, CO CODE server version is 23.5.104 running on a Debian bookworm (12) release.

Please let me know if more information is required - more than happy to help!

**Comment by timar** [comment]
This is not an error. You have not configured extra fonts under `<path_to_NC>/settings/admin/richdocuments`.

**Comment by monochromec** [comment]
Perhaps I wasn't specific enough: The CODE edition consists of an AppImage in which the CB is packaged. So unless you want to modify the AppImage the proposed work-around is not feasible.

Please reopen and forward to the packagers for resolution.
