### ISSUE TITLE
Incorrect header 22.5.301 on releases page

### ISSUE THREAD

**Issue by keestux** [CollaboraOnline/richdocumentscode#240]
The text header for release 23.5.301 is "22.5.301". But all the links seem to be OK.

https://github.com/CollaboraOnline/richdocumentscode/releases

**Comment by joshtrichards** [comment]
Confirmed, but I can't fix since my permissions are limited to the Nextcloud org on GH. Hopefully someone else will come along that can fix this here:

https://github.com/CollaboraOnline/richdocumentscode/releases/tag/23.5.301

**Comment by timur-g** [comment]
Corrected. Thanks.
