### ISSUE TITLE
Zotero support?

### ISSUE THREAD

**Issue by Lawkss** [CollaboraOnline/richdocumentscode#242]
"Zotero - This instance does not support Zotero, because the feature is missing or disabled. Please contact the admin"

Is this only supported in the regular collabora online? Will it come to CODE of if it is already available how can I enable it?

**Comment by eszkadev** [comment]
Zotero should be available in CODE too. It requires to use integration which also supports our Zotero integration (we need to pass correct Zotero API key to CODE for a current user).
Which integration do you use (storage provider) ?

**Comment by Lawkss** [comment]
I don't think I understand what you mean. 

I use the inbuilt self hosted development version. 

Sometimes the menu on the left will say "Nextcloud office" and it will say that Zotero is not available. 

For reasons I dont know, after a while, visiting the Page it will suddenly just say "Office" and then it will let me put the Zotero Api. 

Anyway it seems to work now, even when it reverts to "nextcloud office" and then saying zotero is not available. When the menu option changes again it will show my saved API key.
