### ISSUE TITLE
Error being thrown to log Error Call to undefined method OCA\Richdocuments\Service\DiscoveryService::refetch() Could not boot richdocuments: Call to undefined method OCA\Richdocuments\Service\DiscoveryService::refetch()

### ISSUE THREAD

**Issue by MatthiasGer0821** [CollaboraOnline/richdocumentscode#256]
The following bug, which was fixed here (https://github.com/nextcloud/richdocuments/issues/3363) also shows up
in the Built-in CODE Server.

**Since the bug was fixed there, please apply the fix here also.**

The following is the description:
Getting the following error thrown to the log every few seconds. It doesn't seem to be affecting any of my workloads but I'd like to try and identify how to solve it

Error Call to undefined method OCA\Richdocuments\Service\DiscoveryService::refetch()
Could not boot richdocuments: Call to undefined method OCA\Richdocuments\Service\DiscoveryService::refetch()

To Reproduce

Go to admin settings
scroll down to logging
error is presented
Expected behavior

unsure

Screenshots

![Screenshot 2023-12-29 115130](https://github.com/CollaboraOnline/richdocumentscode/assets/89694669/684d2430-0fa0-4771-b1f2-9066fbb37c2e)

Log: 
{
  "reqId": "aotXjCZpSlFyOnqxkmgS",
  "level": 4,
  "time": "2023-12-16T13:13:08+00:00",
  "remoteAddr": "192.168.55.4",
  "user": "Jeef",
  "app": "no app in context",
  "method": "GET",
  "url": "/index.php/apps/logreader/api/poll?lastReqId=",
  "message": "Could not boot richdocuments: Call to undefined method OCA\\Richdocuments\\Service\\DiscoveryService::refetch()",
  "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0",
  "version": "28.0.1.0",
  "exception": {
    "Exception": "Error",
    "Message": "Call to undefined method OCA\\Richdocuments\\Service\\DiscoveryService::refetch()",
    "Code": 0,
    "Trace": [
      {
        "file": "/var/www/html/nextcloud/apps/richdocuments/lib/AppInfo/Application.php",
        "line": 154,
        "function": "checkAndEnableCODEServer",
        "class": "OCA\\Richdocuments\\AppInfo\\Application",
        "type": "->"
      },
      {
        "file": "/var/www/html/nextcloud/lib/private/AppFramework/Bootstrap/Coordinator.php",
        "line": 200,
        "function": "boot",
        "class": "OCA\\Richdocuments\\AppInfo\\Application",
        "type": "->"
      },
      {
        "file": "/var/www/html/nextcloud/lib/private/App/AppManager.php",
        "line": 434,
        "function": "bootApp",
        "class": "OC\\AppFramework\\Bootstrap\\Coordinator",
        "type": "->"
      },
      {
        "file": "/var/www/html/nextcloud/lib/private/App/AppManager.php",
        "line": 213,
        "function": "loadApp",
        "class": "OC\\App\\AppManager",
        "type": "->"
      },
      {
        "file": "/var/www/html/nextcloud/lib/private/legacy/OC_App.php",
        "line": 125,
        "function": "loadApps",
        "class": "OC\\App\\AppManager",
        "type": "->"
      },
      {
        "file": "/var/www/html/nextcloud/lib/base.php",
        "line": 1049,
        "function": "loadApps",
        "class": "OC_App",
        "type": "::"
      },
      {
        "file": "/var/www/html/nextcloud/index.php",
        "line": 39,
        "function": "handleRequest",
        "class": "OC",
        "type": "::"
      }
    ],
    "File": "/var/www/html/nextcloud/apps/richdocuments/lib/AppInfo/Application.php",
    "Line": 226,
    "message": "Could not boot richdocuments: Call to undefined method OCA\\Richdocuments\\Service\\DiscoveryService::refetch()",
    "exception": {},
    "CustomMessage": "Could not boot richdocuments: Call to undefined method OCA\\Richdocuments\\Service\\DiscoveryService::refetch()"
  }
}

**Comment by MatthiasGer0821** [comment]
I´m aware that it´s not been to long, plus there was a turn of the year, but I´d really apreciate an update if someone can help or point me in the right direction. The error keeps accumulating (see picture). 

I´d like to know if this is something to worry about or where I should address this. 
Online editing seems to work, but i´m worried about data loss. 

![image](https://github.com/CollaboraOnline/richdocumentscode/assets/89694669/14182482-e52f-4b87-9a62-82d23c3a2775)

**Comment by mokkin** [comment]
I have the same version and problem on our instance.

**Comment by MatthiasGer0821** [comment]
I once again want to ask if someone could tell me how serious this error is or what I could do that this can be looked at. 
I´d have to switch to another solution otherwise :-/

**Comment by MatthiasGer0821** [comment]
For some reason, the issue seems to be fixed in the new vesion 23.5.702 (although i cannot confirm this by looking at the changed code)
Can anybody confirm this or  
@timar can you maybe comment ? Would be highly appreciated
