### ISSUE TITLE
In spreadsheet comments long date is always formatted as M/D/Y type.

### ISSUE THREAD

**Issue by kamilko** [CollaboraOnline/richdocumentscode#257]
How to reproduce:
- have your zone date format as D/M/Y
- add comment (while doing this, comment date will be displayed properly)
- save comment and then display comment tooltip
- date format will be always as M/D/Y

This was tested on many different version of Nextcloud as well as many different version of OS (mostly Debian and Ubuntu, also snap version of Nextcloud).
Also it doesn't matter what locale is on server or user system, as long it isn't M/D/Y.

**Comment by joshtrichards** [comment]
Is this reproducible with text or md documents by chance?

This sounds like an issue in Nextcloud Server itself or richdocuments, but not CODE or richdocumentscode (but anything's possible).

Would you mind popping over to the [richdocuments](https://github.com/nextcloud/richdocument) repository and creating an Issue for this? Please post a screenshot when you do so.

**Comment by timur-g** [comment]
I reproduce this with NC 27.1.5 and Online 23.05.8, meaning that is not Built-in CODE specific, which is this repo. 
So this should be closed, best after report is created. I cannot test at the moment if this is Collabora Online or Nextcloud Richdocuments issue.

**Comment by kamilko** [comment]
OK
I will report this to richdocuments then.
Thank you.

**Comment by timur-g** [comment]
Not sure that is RD, how to know? Because format of a comment date should come from a cell format, like 12/31 and comment likerally shows it like that. What we expect is that is read in accordance with our locale setting . If that is NC in a language that normally uses 31.12., we would like to see "31 Dec". Not sure if Online or RD should do that.

**Comment by timur-g** [comment]
https://github.com/nextcloud/richdocuments/issues/3447
