### ISSUE TITLE
Collabora Update deletes contents of text files and tables

### ISSUE THREAD

**Issue by bisam2000** [CollaboraOnline/richdocumentscode#259]
I have repeatedly noticed that updating Collabora Online Built-in CODE Server deletes the contents of Collabora files (documents and tables). This occurs with files that were newly created in Collabora shortly before the update. The file itself remains, but it no longer has any content after the update. The file version management also only shows empty files.
I'm currently using Nextcloud 27.1.5. Before updating to Collabora Online - Built-in CODE Sever 23.5.705 I created a test file (text file) and wrote a few lines of text. Of course I saved the file. After the update, the file was still there, but the contents had been deleted again.

**Comment by timur-g** [comment]
Sounds like #238. It is not about update, but first save.
If you test differently, please explain.
