### ISSUE TITLE
Warning “formula separator settings conflict with locale” after update to 24.x

### ISSUE THREAD

**Issue by flatterrich** [CollaboraOnline/richdocumentscode#268]
https://forum.collaboraonline.com/t/warning-formula-separator-settings-conflict-with-locale-after-update-to-24-x/2564
or
https://help.nextcloud.com/t/warning-formula-separator-settings-conflict-with-locale-after-update-to-24-x/189032/2
see forums for details

**Comment by m4nges** [comment]
Same here.

**Comment by flatterrich** [comment]
With 24.4.201 bug was fixed

**Comment by thebearon** [comment]
Indeed, this has been fixed, see https://github.com/CollaboraOnline/online/issues/8863 for more information.
