### ISSUE TITLE
http_response_code(): Cannot set response code - headers already sent 

### ISSUE THREAD

**Issue by modir** [CollaboraOnline/richdocumentscode#270]
I did now an update to the latest version of CollaboraOnline and now it is not possible anymore to open files. The log is filled with this warning:

`PHP Warning:  http_response_code(): Cannot set response code - headers already sent (output started at /srv/httpd/nextcloud/apps/richdocumentscode/proxy.php:285) in /srv/httpd/nextcloud/apps/richdocumentscode/proxy.php on line 292`

It is very likely this is the problem.

**Comment by modir** [comment]
Wrong repo. Sorry my mistake

**Comment by michnovka** [comment]
Why was this closed? Where did you end up reporting @modir 
I see there was an issue https://github.com/nextcloud/richdocuments/issues/3699 but you were told to open it here. Now here it is closed. So where can I track this?

I have the same issue on my nextcloud

**Comment by modir** [comment]
@michnovka In the end a full reboot solved the problem. The software behind the proxy sent something in the newer version which the "old" proxy didn't like. So once I rebooted I had the new Collabora and the new proxy and the problem disappeared.

**Comment by derRichter** [comment]
here the same error. i wondered me to, what is the reason to close this bug without answer or fix?

get error:
`PHP Warning:  http_response_code(): Cannot set response code - headers already sent (output started at /var/www/nextcloud/apps/richdocumentscode/proxy.php:289) in /var/www/nextcloud/apps/richdocumentscode/proxy.php on line 296`

upgraed to  Collabora Online - Built-in CODE Server
Version 24.4.802, APACHE-lizensiert 

full reboot the hole server

error and bug, still exist!

**Comment by giox069** [comment]
Same problem here, and a full reboot of the server did not solved it.
I deleted line [296](https://github.com/CollaboraOnline/richdocumentscode/blob/4343b0770ce0b0fb205837f270dbbf52eacc4735/proxy.php#L296) http_response_code(200); and now I can open .odt files again.
The code seems to be incorrect, because there are some "print" just before http_response_code(200);
Can anyone fix it ? Is my solution to delete that line right ?

**Comment by timar** [comment]
Fixed in 24.4.1103
