### ISSUE TITLE
wrong directory when accessing a file

### ISSUE THREAD

**Issue by LuCu11** [CollaboraOnline/richdocumentscode#272]
Hi folks,

I get an error when I try to open a file under Nextcloud. The loading circle is displayed, but no file is loaded. The Apache log shows the following entry:
`AH00128: File does not exist: /var/www/html/apps/files/api/v1/views`
The following entry can be seen in the Nextcloud log:
`{"reqId":"sNy0lW7qlXEP8e7CHpOi","level":3,"time":"2024-06-13T05:44:23+00:00","remoteAddr":"188.193.111.35","user":"--","app":"index","method":"GET","url":"/apps/files/api/v1/views","message":"The requested uri(/apps/files/api/v1/views) cannot be processed by the script '/cloud/index.php')","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:126.0) Gecko/20100101 Firefox/126.0","version":"29.0.2.2","exception":{"Exception":"Exception","Message":"The requested uri(/apps/files/api/v1/views) cannot be processed by the script '/cloud/index.php')","Code":0,"Trace":[{"file":"/var/www/html/cloud/lib/base.php","line":1003,"function":"getRawPathInfo","class":"OC\\AppFramework\\Http\\Request","type":"->"},{"file":"/var/www/html/cloud/index.php","line":49,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/html/cloud/lib/private/AppFramework/Http/Request.php","Line":743,"message":"The requested uri(/apps/files/api/v1/views) cannot be processed by the script '/cloud/index.php')","exception":{},"CustomMessage":"The requested uri(/apps/files/api/v1/views) cannot be processed by the script '/cloud/index.php')"}}`

What is strange is that the directory path specified in apache.log is actually wrong, it should be "/var/www/html/cloud/apps/files/api/v1/views". There seems to be an incorrect path somewhere. 

Maybe one of you can help me?

**Comment by LuCu11** [comment]
additional, maybe important info, nextcloud is installed in the directory /var/www/html/cloud

**Comment by joshtrichards** [comment]
This is likely a Nextcloud configuration matter. I suggest posting the details of your environment and config on the help forum - https://help.nextcloud.com

It may have to do with your `overwritewebroot` setting or possibly the web server config.
