### ISSUE TITLE
Failed Integrity Check pkcs11.txt

### ISSUE THREAD

**Issue by Jeefongithub** [CollaboraOnline/richdocumentscode#273]
I'm presented the following error about a failed integrity check

Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- richdocumentscode
	- EXTRA_FILE
		- pkcs11.txt

Raw output
==========
Array
(
    [richdocumentscode] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [pkcs11.txt] => Array
                        (
                            [expected] => 
                            [current] => a267334eb74f95b95879be3ca5bd7f897d7a9de2acd7d8f076d34a7c4e3a1afbd903db200a788b3f2c5908ebc1b1ce658eeaf76f35664fa28590b374a9bf5d42
                        )

                )

        )

)

**Comment by joshtrichards** [comment]
That file (`pkcs11.txt`) didn't come from this package. May want to check the file date/etc and see if you can figure out where it came from. For the purposes of the integrity check of `richdocumentscode` you can safely remove (or move elsewhere) that file.

**Comment by Jeefongithub** [comment]
moved file and rescanned. Can confirm app is functioning properly and error is no longer present. Not sure where it came from but I'll dig into it. Thanks!
