### ISSUE TITLE
Built-in CODE server triggers mod-evasive

### ISSUE THREAD

**Issue by jimbolaya** [CollaboraOnline/richdocumentscode#276]
I recently moved my Nextcloud to a new server and in the interest of trying to reduce my administrative tasks, moved from using the external CODE server using packages from the collaboraonline server with a reverse proxy to the built in CODE server from apps.nextcloud.

I found if I have mod-evasive installed, when I click on a very simple test document (18KB) it appears to almost load (with the Loading screen), then shows the editing "ribbon" and sometimes part of the text, but then very quickly goes to a blank page with the bar with the Nextcloud logo in it and nothing else.

I get the message "The server has been disconnected." and "You has left" in the upper right.

It reloads this way if I navigate away from the page and navigate back.

If I disable mod-evasive in Apache2, then it works fine. 

Does anyone have a magic configuration for mod-evasive for this?

**Comment by joshtrichards** [comment]
Hi @jimbolaya - This question is better suited for the Nextcloud Help Forum (https://help.nextcloud.com) or Collabora Forum or perhaps even mod_evasive community help forums/channels.

This channel (here) is intended for reporting bugs in the Built-in CO app itself that require developer attention, not technical support or general troubleshooting.

Please close this issue out when you get a chance. Thanks!

**Comment by jimbolaya** [comment]
Thanks. I guess since this is the only web app I run that triggers mod-evasive, I could get some insight. 

I'll see what I can find elsewhere.

**Comment by jimbolaya** [comment]
.

**Comment by jimbolaya** [comment]
Thanks. I guess since this is the only web app I run that triggers mod-evasive, I could get some insight. 

I'll see what I can find elsewhere.
