### ISSUE TITLE
Refuses to install on my AWS node

### ISSUE THREAD

**Issue by SuperCuber** [CollaboraOnline/richdocumentscode#34]
Using latest NextCloud and Collabora Online app, trying to install `Collabora Online - Built-in CODE Server` 

When I click "Download and Enable", after about a minute it just fails without producing any message (doesn't change the "Download and enable" button into "Disable" as expected, and the app doesn't get installed)

Not sure what I'm doing wrong - I've installed Docker on my host and can even run `docker pull collabora/code` successfully (only from root though)

**Comment by SuperCuber** [comment]
Update: I checked the logs, there's this error message: 
```
Allowed memory size of 134217728 bytes exhausted (tried to allocate 314315496 bytes) at /var/www/cloud/lib/private/Installer.php#285
```
My node has 1GB of RAM, could that be the issue?

**Comment by kendy** [comment]
@SuperCuber: No, I don't think the actual RAM is the issue, rather I think you forgot to set the PHP memory limit as Nextcloud recommends (512M). You can either raise that, or install manually using the occ command like:

php -d memory_limit=512M occ app:install richdocumentscode

**Comment by SuperCuber** [comment]
Changed php.ini accordingly and restarted and it works properly, thanks.
