### ISSUE TITLE
Cannot use on two instances, cannot create new documents

### ISSUE THREAD

**Issue by nursoda** [CollaboraOnline/richdocumentscode#37]
I installed the two collabora apps (4.2.405, 3.7.0) on two NGINX/PHP-FPM sites / NC 19 instances, both on one Arch linux server (all current): first on my test instance, then on my family instance. Although setup was without errors, I now cannot not open any document on the family server, and I cannot manually start the AppImage: "access denied" …?? It is unpacked in /tmp … do richdocumentscode on two NC instances on the same server interfere?

Also, I could not create ANY new document in the web interface. On the test system, I get (back-translated to english): "Loading of document failed. Make sure that this file type is supported and that the file is not broken, then try again." – a weird message for a file just created by the app itself.

The file is created nonetheless, and being synced to my desktop from where I may open it using LibreOffice just fine, so it's valid ods/odt.

In case that's relevant:

- I had OnlyOffice community document server before that, and that also created template links. But it created xlsx/docs, so I think the templates are from collabora. But I deactivated both prior to installing the two Collabora apps richdocuments and richdocumentscode.
- I have no templates set up in the config sections, neither as admin nor as user.

**Comment by timar** [comment]
It is not possible to run two richdocumentscode instances on the same server, because both want to bind to port 9983.

**Comment by nursoda** [comment]
Thanks for clarification. Would it be possible to allow using sockets instead of ports?
