### ISSUE TITLE
latest version 4.2.406 stopped working

### ISSUE THREAD

**Issue by nextgen-networks** [CollaboraOnline/richdocumentscode#39]
Hey devs!
Collabora was working perfectly until its update today from 4.2.405 -> 4.2.406.

When opening a document it fist showed a message to wait because CODE server is beeing started.
... after wating for more than 10 minutes and reload I've got a 504 in the collabora frame (althought nextcloud was loaded successfully).

Here is what i found in the NC logs:
`[richdocuments] Error: GuzzleHttp\Exception\ConnectException: cURL error 28: Operation timed out after 45000 milliseconds with 0 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) at <<closure>>

 0. /var/www/vhosts/ReplacedVHostNameAndPath/apps/files_external_onedrive/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php line 155
    GuzzleHttp\Handler\CurlFactory::createRejection(GuzzleHttp\Handl ... l}, {errno: 28,error ... "})
 1. /var/www/vhosts/ReplacedVHostNameAndPath/apps/files_external_onedrive/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php line 105
    GuzzleHttp\Handler\CurlFactory::finishError(GuzzleHttp\Handler\CurlHandler {}, GuzzleHttp\Handl ... l}, GuzzleHttp\Handler\CurlFactory {})
 2. /var/www/vhosts/ReplacedVHostNameAndPath/apps/files_external_onedrive/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php line 43
    GuzzleHttp\Handler\CurlFactory::finish(GuzzleHttp\Handler\CurlHandler {}, GuzzleHttp\Handl ... l}, GuzzleHttp\Handler\CurlFactory {})
 3. /var/www/vhosts/ReplacedVHostNameAndPath/apps/files_external_onedrive/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php line 28
    GuzzleHttp\Handler\CurlHandler->__invoke("*** sensitive parameter replaced ***", "*** sensitive parameter replaced ***")
 4. /var/www/vhosts/ReplacedVHostNameAndPath/apps/files_external_onedrive/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php line 51
    GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}("*** sensitive parameters replaced ***")
 5. /var/www/vhosts/ReplacedVHostNameAndPath/apps/twofactor_gateway/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php line 37
    GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}("*** sensitive parameters replaced ***")
 6. /var/www/vhosts/ReplacedVHostNameAndPath/apps/files_external_onedrive/vendor/guzzlehttp/guzzle/src/Middleware.php line 29
    GuzzleHttp\PrepareBodyMiddleware->__invoke("*** sensitive parameter replaced ***", "*** sensitive parameter replaced ***")
 7. /var/www/vhosts/ReplacedVHostNameAndPath/apps/files_external_onedrive/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php line 70
    GuzzleHttp\Middleware::GuzzleHttp\{closure}("*** sensitive parameters replaced ***")
 8. /var/www/vhosts/ReplacedVHostNameAndPath/apps/files_external_onedrive/vendor/guzzlehttp/guzzle/src/Middleware.php line 59
    GuzzleHttp\RedirectMiddleware->__invoke("*** sensitive parameter replaced ***", "*** sensitive parameter replaced ***")
 9. /var/www/vhosts/ReplacedVHostNameAndPath/apps/files_external_onedrive/vendor/guzzlehttp/guzzle/src/HandlerStack.php line 67
    GuzzleHttp\Middleware::GuzzleHttp\{closure}("*** sensitive parameters replaced ***")
10. /var/www/vhosts/ReplacedVHostNameAndPath/apps/files_external_onedrive/vendor/guzzlehttp/guzzle/src/Client.php line 277
    GuzzleHttp\HandlerStack->__invoke("*** sensitive parameter replaced ***", "*** sensitive parameter replaced ***")
11. /var/www/vhosts/ReplacedVHostNameAndPath/apps/files_external_onedrive/vendor/guzzlehttp/guzzle/src/Client.php line 125
    GuzzleHttp\Client->transfer("*** sensitive parameter replaced ***", "*** sensitive parameter replaced ***")
12. /var/www/vhosts/ReplacedVHostNameAndPath/apps/files_external_onedrive/vendor/guzzlehttp/guzzle/src/Client.php line 131
    GuzzleHttp\Client->requestAsync("get", GuzzleHttp\Psr7\Uri {}, {verify: true,ti ... }})
13. /var/www/vhosts/ReplacedVHostNameAndPath/lib/private/Http/Client/Client.php line 228
    GuzzleHttp\Client->request("get", "https://ReplacedDomainPart ... y", {verify: true,ti ... e})
14. /var/www/vhosts/ReplacedVHostNameAndPath/apps/richdocuments/lib/WOPI/DiscoveryManager.php line 104
    OC\Http\Client\Client->get("https://ReplacedDomainPart ... y", {timeout: 45,nex ... e})
15. /var/www/vhosts/ReplacedVHostNameAndPath/apps/richdocuments/lib/WOPI/DiscoveryManager.php line 78
    OCA\Richdocuments\WOPI\DiscoveryManager->fetchFromRemote()
16. /var/www/vhosts/ReplacedVHostNameAndPath/apps/richdocuments/lib/WOPI/Parser.php line 41
    OCA\Richdocuments\WOPI\DiscoveryManager->get()
17. /var/www/vhosts/ReplacedVHostNameAndPath/apps/richdocuments/lib/TokenManager.php line 210
    OCA\Richdocuments\WOPI\Parser->getUrlSrc("application/vnd ... t")
18. /var/www/vhosts/ReplacedVHostNameAndPath/apps/richdocuments/lib/Controller/DocumentController.php line 245
    OCA\Richdocuments\TokenManager->getToken("*** sensitive parameters replaced ***")
19. /var/www/vhosts/ReplacedVHostNameAndPath/lib/private/AppFramework/Http/Dispatcher.php line 170
    OCA\Richdocuments\Controller\DocumentController->index("*** sensitive parameter replaced ***", null)
20. /var/www/vhosts/ReplacedVHostNameAndPath/lib/private/AppFramework/Http/Dispatcher.php line 100
    OC\AppFramework\Http\Dispatcher->executeController(OCA\Richdocument ... {}, "index")
21. /var/www/vhosts/ReplacedVHostNameAndPath/lib/private/AppFramework/App.php line 137
    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Richdocument ... {}, "index")
22. /var/www/vhosts/ReplacedVHostNameAndPath/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
    OC\AppFramework\App::main("OCA\\Richdocume ... r", "index", OC\AppFramework\ ... {}, {_route: "richdocuments.document.index"})
23. <<closure>>
    OC\AppFramework\Routing\RouteActionHandler->__invoke({_route: "richdocuments.document.index"})
24. /var/www/vhosts/ReplacedVHostNameAndPath/lib/private/Route/Router.php line 297
    call_user_func(OC\AppFramework\ ... {}, {_route: "richdocuments.document.index"})
25. /var/www/vhosts/ReplacedVHostNameAndPath/lib/base.php line 1007
    OC\Route\Router->match("/apps/richdocuments/index")
26. /var/www/vhosts/ReplacedVHostNameAndPath/index.php line 37
    OC::handleRequest()

GET /index.php/apps/richdocuments/index?fileId=1449846&requesttoken=ReplacedRequestTokenID
from ReplacedRequestIP by ReplacedRequestUserName at 2020-06-23T08:52:33+00:00`

Would be glad if changes that lead to that behavior would be reverted.

Thanks

**Comment by timar** [comment]
AFAIK we have not changed anything that could cause this. [This](https://github.com/CollaboraOnline/richdocumentscode/commit/5e7f2a5601388765f137299cfe38918fc824aca8) was the only difference between 4.2.405 and 4.2.406

**Comment by nextgen-networks** [comment]
This error error appeared on a other machine i've updated to 4.2.406 too:
![image](https://user-images.githubusercontent.com/21206978/85396709-7bf7bb00-b552-11ea-8287-91cc36caf375.png)

Both machines are managed by latest Plesk release 18.0.21 U1.
One is bases on latest Ubuntu 18.04 LTS the other on latest Ubuntu 16.04 LTS.

I saw the command how  to check the status of the appImage is done has been changed.
This check may report a false-positive and let the Collabora app assume CODE-appImage is not started?

I've not restarted the server or one of its services since the update - will do this and report back if it helps ...

**Comment by jlaunay** [comment]
Same here, was working with 4.2.405 and with 4.2.406 I get the following error:

```
$docker logs --tail 100 nextcloud-fpm
dlopen(): error loading libfuse.so.2
AppImages require FUSE to run. 
You might still be able to extract the contents of this AppImage 
if you run it with the --appimage-extract option. 
See https://github.com/AppImage/AppImageKit/wiki/FUSE 
for more information
```

**Comment by nextgen-networks** [comment]
> I've not restarted the server or one of its services since the update - will do this and report back if it helps ...

... before restarting I've checked for remaining plesk updates  - found 18.0.28 (not officially announced yet) updated the server and voilá - CODE was working again.

Conclusion:
If you face issues similar to mine an restart of nginx, apache or php might solve your issues.

@jlaunay:
I think your problem is not close related to the issue i faced here.
Just check the open issue #26 - there is more information collected already for affected docker users

**Comment by nursoda** [comment]
I also see the Socket proxy error, 405 was OK, 406 fails (on my own arch server).

**Comment by jlaunay** [comment]
> @jlaunay:
> I think your problem is not close related to the issue i faced here.
> Just check the open issue #26 - there is more information collected already for affected docker users

I also have the socket proxy error and everything was ok before version 406.
I can't reproduce my previous error with fuse, I think it was because of the tests I was running to find why it didn't work.

**Comment by kyrofa** [comment]
This busted in the snap, too. Running it by hand it fails as well with:

> Failed to listen on Server port(s) (9982-9982). Exiting.

**Comment by kyrofa** [comment]
Things are working again for the snap on 407.

**Comment by nursoda** [comment]
Same here. Document loads again. Saving a document is a bit shaky though. Sometimes doesn't react. Save As seems to work. In some cases, Save as produced a "0 byte" file with the new name however. Re-opening and re-saving it finally wrote it after some attempts.

**Comment by nursoda** [comment]
This bug may be closed. It seems to me that I can't do that.

**Comment by nextgen-networks** [comment]
I like to close this - pls continue in new #43
