### ISSUE TITLE
latest version 4.2.503 stopped working

### ISSUE THREAD

**Issue by nextgen-networks** [CollaboraOnline/richdocumentscode#43]
Hey devs!

CODE is refusing to work again :-/ (see #39)
![image](https://user-images.githubusercontent.com/21206978/86224414-23936f80-bb89-11ea-8bd9-e011e4fde797.png)

Two machines are managed by latest Plesk release 18.0.28.
One is based on latest Ubuntu 18.04 LTS the other on latest Ubuntu 16.04 LTS.

No errors in NC log.

I've restarted the server already but this is no workaround here

**Comment by nextgen-networks** [comment]
... the problem magically(TM) solved itself - on both servers ...

**Comment by nursoda** [comment]
I couldn't believe this, tried, and – yes, loads fine. Why?

Saving seems slow though (OK, different, issue?, anyway). Steps:

- Open existing test document and make a minor change
- close it (using (X) in the Collabora app top right) – I'd expedted that a warning asks to save, or that document is saved – neither happens
- reopen it, minor change is still there (cached)
- press "Save" Icon (in the Collabora app top left) (multiple times) – nothing happens, red dot on save icon remains, and save date/time is the timestamp of the "existing test dokument" (in my case last saved some days ago)
- after a while (< 1 minute?), the document is saved automatically – red dot disappears, timestamp is now, file app shows "now"

Is the conclusion of this, that

- save button does not work
- document is saved from cache every minute

?
