### ISSUE TITLE
Impossible to install app pack : Collabora Online - Built-in CODE Server 

### ISSUE THREAD

**Issue by Kitslap** [CollaboraOnline/richdocumentscode#46]
Hello ! 
My Nextcloud is a personal install, recently migrated from a CentOS VM to a Debian VM.
During the migration process, I've updated it to 19, wanted to test the new collabora integration.
I've never made Collabora Docker setup before, I'm just discovering, so I'm sorry if I've missed something important.
I've check all system requirements in the readme.

Setup : 
OS : Debian GNU/Linux 10
2 vCPU ( Intel(R) Xeon(R) CPU E3-1230 v6 @ 3.50GHz )
2Gb RAM
Apache 2.4.38
PHP 7.3.19
Nextcloud 19.0.1
Collabora App (client) 3.7.3

The issue : 
When I try to install Collabora Online - Built-in CODE Server from nextcloud app store, after few seconds loading there is the following error :  
Error: cURL error 23: Failed writing body (9901 != 16360) (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)
The value of this part "(9901 != 16360)" is changing each try i've made.

I've tried to uninstall Collabora App before and to have installed before to try.
I've tried to install it from web ui and from occ commands.
Here is the following occ command i've tried : 
sudo -u www-data php -d memory_limit=512M occ app:install richdocumentscode

I've tried to increase the memory limit value and it doesn't seem to change anything.
I've tried to increase timeout value in installer.php from the nextcloud library and it doesnt to work neither.

I've already verified every single file's owner to make sure www-data is the owner, and it is.
I've made some search about curl library but did not find anything about it.

Google search did not help me.
I can install other apps from the store without any issue.

I hope I gave enough information.

Thanks for helping,

**Comment by Kitslap** [comment]
I finnaly find out what was the issue.
To help people who have the same issue I'll let this topic here.
My /tmp wasnt large enough. Resized it and it's working now.

**Comment by syntron** [comment]
Hello Kitslap, could you provide the size of your new /tmp? I have a similar problem (see #27 and also #47)
