### ISSUE TITLE
CODE (As "lool") absolutely cramming /tmp full of files

### ISSUE THREAD

**Issue by YaroKasear** [CollaboraOnline/richdocumentscode#47]
So, I have someone doing a bulk upload to Nextcloud, not even using Collabora at all, and my Nextcloud server slowed to a crawl. In investigating I found using du hxd1 /tmp that "lool" was spawning HUNDREDS of GiB worth of temporary files.

Here's an example: 

```
118G    ./lool-cuDS65dirwg9WHRB
118G    ./lool-zGRiWK2iwkrIZDo9
```

I have since disabled CODE and Collabora, because I don't think that's okay. This already bit me once and I didn't know it was this software until it happened again this time. I had spent two hours resizing my / and everything thinking I just didn't allocate enough. 

Until this is fixed I can't use this software. Because that's just plain unacceptable.

**Comment by syntron** [comment]
I'm also interested in a solution for this; see also #27 - it seems to be that the app/tool opens all available documents in the back without user interaction. In my case some PDF files resulted in lots of temporary data. Thus, I have deactivated the app till a solution is found. Similar as in your case, it could otherwise result in server crashes with hard to analyse reason.

**Comment by szimszon** [comment]
I have the same issue with:
Nextcloud 19.0.2
Collabora Online 3.7.3
Collabora Online - Built-in CODE Server 4.2.602
I had to disable it ;(

**Comment by timar** [comment]
We have fixed a quite a few related issues since Sep 2, 2020. Please reopen, if you still see files that are not cleaned up after use in /tmp.

**Comment by syntron** [comment]
> We have fixed a quite a few related issues since Sep 2, 2020. Please reopen, if you still see files that are not cleaned up after use in /tmp.

I just checked it on my nextcloud; it seems to run fine in the tests I did. Thus, it is now enabled again. If I find any error I will report here.

Thanks for the work and the hint to check it again!
