### ISSUE TITLE
Failed to listen on Server port(s)

### ISSUE THREAD

**Issue by probonopd** [CollaboraOnline/richdocumentscode#51]
Trying to run `Collabora_Online.AppImage` by double-clicking it, just nothing seems to happen at all.
On the command line, I get:

```
me@host:~$ '/home/me/Downloads/Collabora_Online.AppImage'
Failed to listen on Server port(s) (9982-9982). Exiting.
```

It would be nice if some dialog box would come up telling the user what is going wrong and why, e.g., that the user has to launch some server first before the AppImage can be used (I am only speculating here).

**Comment by ObiWahn** [comment]
Hi I am trying to use the AppImage from `nextcloud`. The installation runs on port 80 and `https` is added with a second `httpd`. In `nextcloud` I am unable to open documents. Is it necessary to NAT some other port or is the information somehow integrated in into the http traffic?

**Comment by timar** [comment]
You do not have to start Collabora_Online.AppImage from the shell. Nextcloud will start it via proxy.php of richdocumentscode app.
