### ISSUE TITLE
Syntax error: "(" unexpected

### ISSUE THREAD

**Issue by fuzunspm** [CollaboraOnline/richdocumentscode#56]
```
sudo -u www-data apps/richdocumentscode/collabora/Collabora_Online.AppImage
```

produces the error below:

> apps/richdocumentscode/collabora/Collabora_Online.AppImage: 1: apps/richdocumentscode/collabora/Collabora_Online.AppImage: Syntax error: "(" unexpected

I'm on Nextcloud 19 and installed both Built-in Code server and Collabora from app store

**Comment by timar** [comment]
`sudo -u www-data apps/richdocumentscode/collabora/Collabora_Online.AppImage` is not the way how this app is supposed to work.
