### ISSUE TITLE
Make available AppImage for ARM-based platforms

### ISSUE THREAD

**Issue by keunes** [CollaboraOnline/richdocumentscode#58]
Hello,

After installing the CODE Server on a Raspberry Pi successfully but still not being able to enable the CODE Sever in the Collabora Online settings, I dug a bit deeper and discovered the [System requirements](https://github.com/CollaboraOnline/richdocumentscode#system-requirements), which state the following:

> Linux x86-64 platform

Since Raspberry Pies are ARM-based, I guess that's the reason for not being able to launch the CODE Server AppImage. Unfortunately, there is no such mention on the `/settings/admin/richdocumentscode` page. As a first step, it would be good if that page would display a warning if the platform is not x86-64.

But, even better of course, it would be very interesting if the CODE Server would be made ready for ARM devices. Since the Raspberry Pi 4 satisfies all other CODE Server requirements, this would be a great combination.

**Comment by mrkara** [comment]
Hi,

After this PR, a warning should be being displayed if the platform and the app doesn't match: https://github.com/CollaboraOnline/richdocumentscode/pull/63

But be aware that there is no app for ARM64 released yet, so please ignore the broken link on the warning, telling you to install the ARM64 version, for now.

**Comment by keunes** [comment]
Thank you @mrkara for working on this 🙏
Does your reply imply that indeed an ARM version will be made available in future?

**Comment by mrkara** [comment]
> Thank you @mrkara for working on this pray
> Does your reply imply that indeed an ARM version will be made available in future?

Pleasure. Yes.

**Comment by keunes** [comment]
@mrkara I was pointed to this, today: https://apps.nextcloud.com/apps/richdocumentscode_arm64
Does this mean the ARM version is now officially provided?

**Comment by mrkara** [comment]
@keunes We have aarch64 build in the works, and we are testing them on Raspberry Pi 4. You might see different pieces here and there, being prepared to come together for the official support.

**Comment by jkumeboshi** [comment]
When I install and activate the "Collabora Online - Built-in CODE Server (ARM64)" inside a the Nextcloud Doker image I get following error:

```
nextcloud    | Logging at warning level to file: /tmp/loolwsd.JQvyabn8Pn/loolwsd.log 
nextcloud    |
nextcloud    | Logging at warning level to file: /tmp/loolwsd.GM4oybVNIF/loolwsd.log
nextcloud    | Error: loolforkit incorrect user-name: www-data - aborting
nextcloud    | Security: --disable-lool-user-checking failed, loolforkit has some capabilities set.
nextcloud    | Failed to listen on Server port(s) (9982-9982). Exiting.
```

**Comment by timar** [comment]
We have ARM64 releases for a while.
