### ISSUE TITLE
(arm64) "Your system is ARM64, but you have installed the x86_64 version of the app."

### ISSUE THREAD

**Issue by filisko** [CollaboraOnline/richdocumentscode#64]
When I go to settings, I get this notice:
```
Your system is ARM64, but you have installed the x86_64 version of the app. Please remove this, and; Install the correct version from the Nextcloud App Store.
```

I guess it's due to to this line:
https://github.com/CollaboraOnline/richdocumentscode/blob/master/lib/Settings/Admin.php#L41

In "arm64" mode this line equals to:
```php
if ($this->getSection() == 'richdocumentscode_arm64_arm64') {
```

When I manually changed it to:
```php
if ($this->getSection() == 'richdocumentscode_arm64') {
```

The notice disappeared.

This is probably due to `sed` https://github.com/CollaboraOnline/richdocumentscode/blob/master/build-nextcloud-app.sh 

Now, another problem I have is that `richdocuments` app does not properly recognize arm64 arch?. The radio option does not appear. 

Is there an upcoming update in `richdocuments` app that fixes this? 🤔 

---

ok, it seems that:
The `richdocuments` app version I have is 3.7.4, but I compared to master and the issue of richdocuments not recognizing arm64 arch seems to be handled, so waiting for new release should be enough. 👍

**Comment by filisko** [comment]
This PR should fix it: https://github.com/CollaboraOnline/richdocumentscode/pull/65

**Comment by timar** [comment]
#63 fixed it.
