### ISSUE TITLE
Your system is ARM64, but you have installed the x86_64 version of the app. - but ARM64 server install

### ISSUE THREAD

**Issue by dustbro** [CollaboraOnline/richdocumentscode#66]
I'm testing out Collabora for the first time with Nextcloud. I've installed _Collabora Online - Built-in CODE Server (ARM64)_ 4.2.800	on my PI4, as well as _Collabora Online_ 3.7.4.
![collab installed](https://user-images.githubusercontent.com/9417887/92932490-00036580-f413-11ea-9a92-b7fe47949174.png)

In the settings for Built-in CODE Server, I'm getting an error stating the wrong version is installed. 
![server](https://user-images.githubusercontent.com/9417887/92932704-41941080-f413-11ea-820f-1fcf40e9e668.png)

And, as expected, the server is not available to Collabora Online
![COLLAB ONOINE](https://user-images.githubusercontent.com/9417887/92933165-e878ac80-f413-11ea-9cf1-67e4fff9dea7.png)

**Comment by timar** [comment]
Yes, the richdocuments change for ARM64 has not been released. The error message "Your system is ARM64, but you have installed the x86_64 version of the app." is bugus, you can ignore it. For the time being you can configure the URM manually:

(*) Use your own server
http://rpi.test/apps/richdocumentscode_arm64/proxy.php?req=

Instead of rpi.test use your own hostname.

**Comment by aelisya** [comment]
i have the same problem, and when i do that https://nextcloud.mydomain.tld/apps/richdocumentscode_arm64/proxy.php?req= in the myserver box i have connection error after a very long time (with let's encrypt up to date certificate) and the firewall down (just in case). any idea ?

**Comment by treuss** [comment]
Same problem over here...

> i have the same problem, and when i do that https://nextcloud.mydomain.tld/apps/richdocumentscode_arm64/proxy.php?req= in the myserver box i have connection error after a very long time (with let's encrypt up to date certificate) and the firewall down (just in case). any idea ?

**Comment by Floppik** [comment]
> i have the same problem, and when i do that https://nextcloud.mydomain.tld/apps/richdocumentscode_arm64/proxy.php?req= in the myserver box i have connection error after a very long time (with let's encrypt up to date certificate) and the firewall down (just in case). any idea ?

Confirm, same error. 
Linux rock64 4.4.202-1237-rockchip-ayufan-gfd4492386213 #1 SMP Sat Nov 23 13:55:47 UTC 2019 aarch64 GNU/Linux
Nextcloud 19.0.3
Collabora Online - Built-in CODE Server (ARM64)	4.2.800

**Comment by fase1** [comment]
Same error to me.
Also, i miss the possibility to activate the CODE option in the Collabora settings.

Raspi 4B 8GB
RasberryOS 64bit, latest
nextcloudpi 1.30
nextcloud 19.0.3

**Comment by Stufo76** [comment]
Same issue here

**Comment by GiulioZani** [comment]
Same issue here

**Comment by GiulioZani** [comment]
Same issue here.

Raspi 4B 8GB
RasberryOS 64bit, latest
nextcloud 19.0.4

**Comment by Stufo76** [comment]
Same issue here even after Nextcloud update from 19.0.3 to 19.0.4

Raspi 4B 8GB
RasberryOS 64bit, latest
Nextcloud 19.0.4

**Comment by HeyWatchOutDude** [comment]
Same issue.

Device: RPI4 (4GB)
OS: Ubuntu 20.04 LTS (64Bit)
Nextcloud: 19.0.4

**Comment by mikebakke** [comment]
same here unfortunately, no matter what I enter in the URL. Uncertain if :9980 should be starting but certainly for me it isn't

**Comment by HeyWatchOutDude** [comment]
> same here unfortunately, no matter what I enter in the URL. Uncertain if :9980 should be starting but certainly for me it isn't

Was it working on NC Version 19.0.3?

**Comment by mikebakke** [comment]
> > same here unfortunately, no matter what I enter in the URL. Uncertain if :9980 should be starting but certainly for me it isn't
> 
> Was it working on NC Version 19.0.3?

uncertain - 20.0 is the first time I've tried this after hitting a brick wall with OnlyOffice

**Comment by Stufo76** [comment]
Now, just after Collabora update, all is working fine.

Raspberry Pi 4B 8GB
Operating System: Debian GNU/Linux 10 (buster)
Kernel: Linux 5.4.51-v8+
Architecture: arm64
Nextcloud 19.0.4
Collabora Online 3.7.5
Collabora Online - Built-in CODE Server (ARM64) 4.2.900

**Comment by HeyWatchOutDude** [comment]
Yeah it's working now but I can't edit files. (I think also some buttons are missing)

Screenshot: https://imgur.com/a/UTI0916

**Comment by GiulioZani** [comment]
Even after this update, I get an error. Here's what happens:
First time I try to download it i get: "An error occured during the request. Unable to proceed."
Second time succeeds very quickly, but it still still doesn't work, even if I try with the above mentioned hack.

Raspberry Pi 4B 4GB
Operating System: Raspberry pi os
Kernel: Linux 5.4.70-v8+
Architecture: arm64
Nextcloud 19.0.4 on *Docker*
Collabora Online 3.7.5
Collabora Online - Built-in CODE Server (ARM64) 4.2.900

**Comment by Stufo76** [comment]
> Yeah it's working now but I can't edit files. (I think also some buttons are missing)
> 
> Screenshot: https://imgur.com/a/UTI0916

I can do it

**Comment by Stufo76** [comment]
> Even after this update, I get an error. Here's what happens:
> First time I try to download it i get: "An error occured during the request. Unable to proceed."
> Second time succeeds very quickly, but it still still doesn't work, even if I try with the above mentioned hack.
> 
> Raspberry Pi 4B 4GB
> Operating System: Raspberry pi os
> Kernel: Linux 5.4.70-v8+
> Architecture: arm64
> Nextcloud 19.0.4 on *Docker*
> Collabora Online 3.7.5
> Collabora Online - Built-in CODE Server (ARM64) 4.2.900

I have no error, neither any issue, all is just working fine.

**Comment by HeyWatchOutDude** [comment]
> > Yeah it's working now but I can't edit files. (I think also some buttons are missing)
> > 
> > Screenshot: https://imgur.com/a/UTI0916
> 
> I can do it

Could you please provide me a screenshot? (How it should look)

**Comment by GiulioZani** [comment]
> > Even after this update, I get an error. Here's what happens:
> > First time I try to download it i get: "An error occured during the request. Unable to proceed."
> > Second time succeeds very quickly, but it still still doesn't work, even if I try with the above mentioned hack.
> > Raspberry Pi 4B 4GB
> > Operating System: Raspberry pi os
> > Kernel: Linux 5.4.70-v8+
> > Architecture: arm64
> > Nextcloud 19.0.4 on _Docker_
> > Collabora Online 3.7.5
> > Collabora Online - Built-in CODE Server (ARM64) 4.2.900
> 
> I have no error, neither any issue, all is just working fine.

Could be cause you have an older kernel version...

**Comment by Stufo76** [comment]
> > > Yeah it's working now but I can't edit files. (I think also some buttons are missing)
> > > 
> > > Screenshot: https://imgur.com/a/UTI0916
> > 
> > I can do it
> 
> Could you please provide me a screenshot? (How it should look)

Below a screenshot from my Android App. Sorry for desktop version, I can post it later

http://imgur.com/a/u7YRxGr

**Comment by GiulioZani** [comment]
> > > > Even after this update, I get an error. Here's what happens:
> > > > First time I try to download it i get: "An error occured during the request. Unable to proceed."
> > > > Second time succeeds very quickly, but it still still doesn't work, even if I try with the above mentioned hack.
> > > > Raspberry Pi 4B 4GB
> > > > Operating System: Raspberry pi os
> > > > Kernel: Linux 5.4.70-v8+
> > > > Architecture: arm64
> > > > Nextcloud 19.0.4 on _Docker_
> > > > Collabora Online 3.7.5
> > > > Collabora Online - Built-in CODE Server (ARM64) 4.2.900
> > > 
> > > 
> > > I have no error, neither any issue, all is just working fine.
> > 
> > 
> > Could be cause you have an older kernel version...
> 
> It might, although I don't think it is due to the kernel, I think much more likely due to docker...
> Anyway, my kernel is not an older version, it is the latest stable, yours should be testing.

I see I'll try downgrading it

**Comment by HeyWatchOutDude** [comment]
> > > > > Yeah it's working now but I can't edit files. (I think also some buttons are missing)
> 
> > > > > Screenshot: https://imgur.com/a/UTI0916
> 
> > > > 
> 
> > > > 
> 
> > > > I can do it
> 
> > > 
> 
> > > 
> 
> > > Could you please provide me a screenshot? (How it should look)
> 
> > 
> 
> > Below a screenshot from my Android App. Sorry for desktop version, I can post it later
> 
> > 
> 
> > http://imgur.com/a/u7YRxGr
> 
> 
> 
> Below desktop screenshot:
> 
> 
> 
> https://imgur.com/WC9bJai
> 
> https://imgur.com/nYVulU6
> 
> https://imgur.com/obwLrPY

Thanks!
Which OS do you use?
Is it maybe an issue which is related to "Ubuntu 20.04 LTS (64Bit)?
Has anyone the same issue like me?

**Comment by HeyWatchOutDude** [comment]
By the way I have currently the following kernel version installed on my RPI4.

5.4.0-1021-raspi #24-Ubuntu SMP PREEMPT Mon Oct 5 09:59:23 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux

**Comment by Stufo76** [comment]
> > > > > > Yeah it's working now but I can't edit files. (I think also some buttons are missing)
> > 
> > > > > > Screenshot: https://imgur.com/a/UTI0916
> > 
> > > > > 
> > 
> > > > > 
> > 
> > > > > I can do it
> > 
> > > > 
> > 
> > > > 
> > 
> > > > Could you please provide me a screenshot? (How it should look)
> > 
> > > 
> > 
> > > Below a screenshot from my Android App. Sorry for desktop version, I can post it later
> > 
> > > 
> > 
> > > http://imgur.com/a/u7YRxGr
> > 
> > 
> > 
> > Below desktop screenshot:
> > 
> > 
> > 
> > https://imgur.com/WC9bJai
> > 
> > https://imgur.com/nYVulU6
> > 
> > https://imgur.com/obwLrPY
> 
> Thanks!
> Which OS do you use?
> Is it maybe an issue which is related to "Ubuntu 20.04 LTS (64Bit)?
> Has anyone the same issue like me?

Raspberry Pi OS 64 bit stable latest

Linux version 5.4.51-v8+ (dom@buildbot) (gcc version 5.4.0 20160609 (Ubuntu/Linaro 5.4.0-6ubuntu1~16.04.9)) #1333 SMP PREEMPT Mon Aug 10 16:58:35 BST 2020

PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

**Comment by HeyWatchOutDude** [comment]
> > > > > > > Yeah it's working now but I can't edit files. (I think also some buttons are missing)
> > > 
> > > > > > > Screenshot: https://imgur.com/a/UTI0916
> > > 
> > > > > > 
> > > 
> > > > > > 
> > > 
> > > > > > I can do it
> > > 
> > > > > 
> > > 
> > > > > 
> > > 
> > > > > Could you please provide me a screenshot? (How it should look)
> > > 
> > > > 
> > > 
> > > > Below a screenshot from my Android App. Sorry for desktop version, I can post it later
> > > 
> > > > 
> > > 
> > > > http://imgur.com/a/u7YRxGr
> > > 
> > > 
> > > 
> > > Below desktop screenshot:
> > > 
> > > 
> > > 
> > > https://imgur.com/WC9bJai
> > > 
> > > https://imgur.com/nYVulU6
> > > 
> > > https://imgur.com/obwLrPY
> > 
> > Thanks!
> > Which OS do you use?
> > Is it maybe an issue which is related to "Ubuntu 20.04 LTS (64Bit)?
> > Has anyone the same issue like me?
> 
> Raspberry Pi OS 64 bit stable latest
> 
> Linux version 5.4.51-v8+ (dom@buildbot) (gcc version 5.4.0 20160609 (Ubuntu/Linaro 5.4.0-6ubuntu1~16.04.9)) #1333 SMP PREEMPT Mon Aug 10 16:58:35 BST 2020
> 
> PRETTY_NAME="Debian GNU/Linux 10 (buster)"
> NAME="Debian GNU/Linux"
> VERSION_ID="10"
> VERSION="10 (buster)"
> VERSION_CODENAME=buster
> ID=debian
> HOME_URL="https://www.debian.org/"
> SUPPORT_URL="https://www.debian.org/support"
> BUG_REPORT_URL="https://bugs.debian.org/"

I have tested it now on my windows client (chrome browser) no problems overall, maybe a NC client issue? (OS: iOS)

Have you tested it also on an iOS device?

**Comment by Stufo76** [comment]
I haven't iOS client, so I cannot test it. On Windows, Linux and Android client, all is working fine.

**Comment by Stufo76** [comment]
> > > > > > > > Yeah it's working now but I can't edit files. (I think also some buttons are missing)
> > > > 
> > > > > > > > Screenshot: https://imgur.com/a/UTI0916
> > > > 
> > > > > > > 
> > > > 
> > > > > > > 
> > > > 
> > > > > > > I can do it
> > > > 
> > > > > > 
> > > > 
> > > > > > 
> > > > 
> > > > > > Could you please provide me a screenshot? (How it should look)
> > > > 
> > > > > 
> > > > 
> > > > > Below a screenshot from my Android App. Sorry for desktop version, I can post it later
> > > > 
> > > > > 
> > > > 
> > > > > http://imgur.com/a/u7YRxGr
> > > > 
> > > > 
> > > > 
> > > > Below desktop screenshot:
> > > > 
> > > > 
> > > > 
> > > > https://imgur.com/WC9bJai
> > > > 
> > > > https://imgur.com/nYVulU6
> > > > 
> > > > https://imgur.com/obwLrPY
> > > 
> > > Thanks!
> > > Which OS do you use?
> > > Is it maybe an issue which is related to "Ubuntu 20.04 LTS (64Bit)?
> > > Has anyone the same issue like me?
> > 
> > Raspberry Pi OS 64 bit stable latest
> > 
> > Linux version 5.4.51-v8+ (dom@buildbot) (gcc version 5.4.0 20160609 (Ubuntu/Linaro 5.4.0-6ubuntu1~16.04.9)) #1333 SMP PREEMPT Mon Aug 10 16:58:35 BST 2020
> > 
> > PRETTY_NAME="Debian GNU/Linux 10 (buster)"
> > NAME="Debian GNU/Linux"
> > VERSION_ID="10"
> > VERSION="10 (buster)"
> > VERSION_CODENAME=buster
> > ID=debian
> > HOME_URL="https://www.debian.org/"
> > SUPPORT_URL="https://www.debian.org/support"
> > BUG_REPORT_URL="https://bugs.debian.org/"
> 
> I have tested it now on my windows client (chrome browser) no problems overall, maybe a NC client issue? (OS: iOS)
> 
> Have you tested it also on an iOS device? 

I haven't iOS client, so I cannot test it. On Windows, Linux and Android client, all is working fine.

**Comment by HeyWatchOutDude** [comment]
> > > > > > > > > Yeah it's working now but I can't edit files. (I think also some buttons are missing)
> > > > > 
> > > > > > > > > Screenshot: https://imgur.com/a/UTI0916
> > > > > 
> > > > > > > > 
> > > > > 
> > > > > > > > 
> > > > > 
> > > > > > > > I can do it
> > > > > 
> > > > > > > 
> > > > > 
> > > > > > > 
> > > > > 
> > > > > > > Could you please provide me a screenshot? (How it should look)
> > > > > 
> > > > > > 
> > > > > 
> > > > > > Below a screenshot from my Android App. Sorry for desktop version, I can post it later
> > > > > 
> > > > > > 
> > > > > 
> > > > > > http://imgur.com/a/u7YRxGr
> > > > > 
> > > > > 
> > > > > 
> > > > > Below desktop screenshot:
> > > > > 
> > > > > 
> > > > > 
> > > > > https://imgur.com/WC9bJai
> > > > > 
> > > > > https://imgur.com/nYVulU6
> > > > > 
> > > > > https://imgur.com/obwLrPY
> > > > 
> > > > Thanks!
> > > > Which OS do you use?
> > > > Is it maybe an issue which is related to "Ubuntu 20.04 LTS (64Bit)?
> > > > Has anyone the same issue like me?
> > > 
> > > Raspberry Pi OS 64 bit stable latest
> > > 
> > > Linux version 5.4.51-v8+ (dom@buildbot) (gcc version 5.4.0 20160609 (Ubuntu/Linaro 5.4.0-6ubuntu1~16.04.9)) #1333 SMP PREEMPT Mon Aug 10 16:58:35 BST 2020
> > > 
> > > PRETTY_NAME="Debian GNU/Linux 10 (buster)"
> > > NAME="Debian GNU/Linux"
> > > VERSION_ID="10"
> > > VERSION="10 (buster)"
> > > VERSION_CODENAME=buster
> > > ID=debian
> > > HOME_URL="https://www.debian.org/"
> > > SUPPORT_URL="https://www.debian.org/support"
> > > BUG_REPORT_URL="https://bugs.debian.org/"
> > 
> > I have tested it now on my windows client (chrome browser) no problems overall, maybe a NC client issue? (OS: iOS)
> > 
> > Have you tested it also on an iOS device? 
> 
> I haven't iOS client, so I cannot test it. On Windows, Linux and Android client, all is working fine.

Anyone else?

**Comment by sunjam** [comment]
Armbian 20.08.3 Buster with Linux 5.8.10-meson64 on Odroid C2 with 2gb ram.
NextcloudPi 20.0.0 with Collabora 4.2.900

Installations now succeeds (!), but unable to actually open files after creation in Files app.
`Failed to load Collabora Online - please try again later✖`

**Comment by timar** [comment]
I'm afraid the conversation diverged quite a lot from the original report, that has been fixed for long.
