### ISSUE TITLE
arm64 Collabora_Online.AppImage: error while loading shared libraries: libz.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by CactiChameleon9** [CollaboraOnline/richdocumentscode#68]
I am trying to run the server on a pi 4 64 bit OS(with nextcloud). I changed the collabora server url manually as directed, and yet it still said a server is not running. So I tried to run the app image directly to test it was working, and I get the following error:

`richdocumentscode_arm64/collabora/Collabora_Online.AppImage: error while loading shared libraries: libz.so: cannot open shared object file: No such file or directory`

Am I doing something wrong, or do I need to install something that provides libz.so?

**Comment by CactiChameleon9** [comment]
OK... I am not sure what was wrong, but doing this fixed it: 
`sudo link /lib/aarch64-linux-gnu/libz.so.1 /lib/aarch64-linux-gnu/libz.so`

**Comment by timar** [comment]
See: https://github.com/AppImage/AppImageKit/issues/964

**Comment by timar** [comment]
We found a solution. If we build `appimagetool` natively on aarch64 platform, then we don't have the dependency to libz.so. (Upstream cross-compiles it.) The next app release will use this method. Until that the [workaround](https://github.com/CollaboraOnline/richdocumentscode/issues/68#issuecomment-692860752) can be used.

**Comment by CactiChameleon9** [comment]
Great.. Thanks. Despite the link I still could not get it to work properly. I used the url listed and modified it to work correctly with my server config but the nextcloud client app refused to connect to the server... I just switched to onlyoffice with qemu. I am happy to do some debugging to get this working however, should I make a new issue?

**Comment by timar** [comment]
Thanks, your help is appreciated. I think the libz.so issue is fixed. We will release a new version soon, and next version of richdocuments and Nextcloud core will have proper support of this new platform (arm64) of Collabora app. Please check it again in a few weeks.

**Comment by CactiChameleon9** [comment]
I got it working now... I just installed libnss3 (causing an error without) and ran the appimage manually, and specified the ip and port in the server url

**Comment by timar** [comment]
> I got it working now... I just installed libnss3 (causing an error without) and ran the appimage manually, and specified the ip and port in the server url

Yeah, libnss3. Thanks for the testing, I hope we can get rid of this dependency, too.
