### ISSUE TITLE
Error Occured during the request.  Unable to proceed.  Could not extract app richdocumentscode_arm64

### ISSUE THREAD

**Issue by sunjam** [CollaboraOnline/richdocumentscode#70]
Error when attempting to appstore download and enable `/index.php/settings/apps/office/richdocumentscode_arm64`

![image](https://user-images.githubusercontent.com/1787238/93716073-2ff0ee00-fb22-11ea-84ca-c0ae03f4b72b.png)

NextcloudPi on arm64 Odroid C2 running Nextcloud 20.0.0beta4.

**Comment by hyphone** [comment]
Do you have enough disc space?
I didn't have this error but a timeout before the download was complete. I had to install it via CLI like `php ./occ app:install richdocumentscode_arm64`

**Comment by sunjam** [comment]
I have enough disk space.  Installation succeeds as of 4.2.900
