### ISSUE TITLE
loolwsd and unprivileged LXC Containers...

### ISSUE THREAD

**Issue by marcogaio** [CollaboraOnline/richdocumentscode#72]
I've installed Collabora Online on a debian buster LXC unprivilegend container mostly following NextCloud info in https://nextcloud.com/collaboraonline/; loolwsd start as expected, Nextclud connect to the instance but when i try to open a document i got:
```
Sep 25 15:27:42 vnclpb1 loolwsd[14250]: /usr/bin/loolmount: mount failed remount [/opt/lool/child-roots/ridzJ5vsTwBcah6P] readonly: Permission denied.
Sep 25 15:27:42 vnclpb1 loolwsd[14250]: kit-15540-14256 2020-09-25 13:27:42.797451 [ kit_spare_002 ] ERR  Failed to mount [/opt/lool/systemplate] -> [/opt/lool/child-roots/ridzJ5vsTwBcah6P/] readonly.| common/JailUtil.cpp:59
Sep 25 15:27:42 vnclpb1 loolwsd[14250]: kit-15540-14256 2020-09-25 13:27:42.797520 [ kit_spare_002 ] WRN  Failed to mount [/opt/lool/systemplate] -> [/opt/lool/child-roots/ridzJ5vsTwBcah6P/], will link/copy contents.| kit/Kit.cpp:2149
Sep 25 15:27:42 vnclpb1 loolwsd[14250]: /usr/bin/loolmount: forced unmount of [/opt/lool/child-roots/ridzJ5vsTwBcah6P/tmp] failed: Permission denied.
Sep 25 15:27:42 vnclpb1 loolwsd[14250]: kit-15540-14256 2020-09-25 13:27:42.827965 [ kit_spare_002 ] ERR  Failed to unmount [/opt/lool/child-roots/ridzJ5vsTwBcah6P/tmp].| common/JailUtil.cpp:70
Sep 25 15:27:42 vnclpb1 loolwsd[14250]: /usr/bin/loolmount: forced unmount of [/opt/lool/child-roots/ridzJ5vsTwBcah6P/lo] failed: Permission denied.
Sep 25 15:27:42 vnclpb1 loolwsd[14250]: kit-15540-14256 2020-09-25 13:27:42.847363 [ kit_spare_002 ] ERR  Failed to unmount [/opt/lool/child-roots/ridzJ5vsTwBcah6P/lo].| common/JailUtil.cpp:70
Sep 25 15:27:42 vnclpb1 systemd[15367]: opt-lool-child\x2droots-ridzJ5vsTwBcah6P.mount: Succeeded.
Sep 25 15:27:42 vnclpb1 systemd[1]: opt-lool-child\x2droots-ridzJ5vsTwBcah6P.mount: Succeeded.
Sep 25 15:27:42 vnclpb1 loolwsd[14250]: /usr/bin/loolmount: forced unmount of [/opt/lool/child-roots/ridzJ5vsTwBcah6P] failed: Permission denied.
Sep 25 15:27:42 vnclpb1 loolwsd[14250]: kit-15540-14256 2020-09-25 13:27:42.880200 [ kit_spare_002 ] ERR  Failed to unmount [/opt/lool/child-roots/ridzJ5vsTwBcah6P/].| common/JailUtil.cpp:70
Sep 25 15:27:43 vnclpb1 loolwsd[14250]: kit-15540-14256 2020-09-25 13:27:43.283542 [ kit_spare_002 ] ERR  mknod(/opt/lool/child-roots/ridzJ5vsTwBcah6P//tmp/dev/random) failed. Mount must not use nodev flag. (EPERM: Operation not permitted)| common/JailUtil.cpp:228
Sep 25 15:27:43 vnclpb1 loolwsd[14250]: kit-15540-14256 2020-09-25 13:27:43.283625 [ kit_spare_002 ] ERR  mknod(/opt/lool/child-roots/ridzJ5vsTwBcah6P//tmp/dev/urandom) failed. Mount must not use nodev flag. (EPERM: Operation not permitted)| common/JailUtil.cpp:240
Sep 25 15:27:43 vnclpb1 loolwsd[14250]: /usr/bin/loolmount: mount failed remount [/opt/lool/child-roots/Il1oS2dgPsdODGa9] readonly: Permission denied.
Sep 25 15:27:43 vnclpb1 loolwsd[14250]: kit-15573-14256 2020-09-25 13:27:43.557557 [ kit_spare_003 ] ERR  Failed to mount [/opt/lool/systemplate] -> [/opt/lool/child-roots/Il1oS2dgPsdODGa9/] readonly.|
+common/JailUtil.cpp:59
Sep 25 15:27:43 vnclpb1 loolwsd[14250]: kit-15573-14256 2020-09-25 13:27:43.557623 [ kit_spare_003 ] WRN  Failed to mount [/opt/lool/systemplate] -> [/opt/lool/child-roots/Il1oS2dgPsdODGa9/], will link/copy
+contents.| kit/Kit.cpp:2149
Sep 25 15:27:43 vnclpb1 loolwsd[14250]: /usr/bin/loolmount: mount failed remount [/opt/lool/child-roots/XuuVkTQOzdi6lfl4] readonly: Permission denied.
Sep 25 15:27:43 vnclpb1 loolwsd[14250]: kit-15574-14256 2020-09-25 13:27:43.564909 [ kit_spare_004 ] ERR  Failed to mount [/opt/lool/systemplate] -> [/opt/lool/child-roots/XuuVkTQOzdi6lfl4/] readonly.|
+common/JailUtil.cpp:59
Sep 25 15:27:43 vnclpb1 loolwsd[14250]: kit-15574-14256 2020-09-25 13:27:43.564977 [ kit_spare_004 ] WRN  Failed to mount [/opt/lool/systemplate] -> [/opt/lool/child-roots/XuuVkTQOzdi6lfl4/], will link/copy
+contents.| kit/Kit.cpp:2149
Sep 25 15:27:43 vnclpb1 loolwsd[14250]: /usr/bin/loolmount: forced unmount of [/opt/lool/child-roots/Il1oS2dgPsdODGa9/tmp] failed: Permission denied.
Sep 25 15:27:43 vnclpb1 loolwsd[14250]: kit-15573-14256 2020-09-25 13:27:43.600571 [ kit_spare_003 ] ERR  Failed to unmount [/opt/lool/child-roots/Il1oS2dgPsdODGa9/tmp].| common/JailUtil.cpp:70
Sep 25 15:27:43 vnclpb1 loolwsd[14250]: /usr/bin/loolmount: forced unmount of [/opt/lool/child-roots/XuuVkTQOzdi6lfl4/tmp] failed: Permission denied.
Sep 25 15:27:43 vnclpb1 loolwsd[14250]: kit-15574-14256 2020-09-25 13:27:43.603914 [ kit_spare_004 ] ERR  Failed to unmount [/opt/lool/child-roots/XuuVkTQOzdi6lfl4/tmp].| common/JailUtil.cpp:70
Sep 25 15:27:43 vnclpb1 loolwsd[14250]: /usr/bin/loolmount: forced unmount of [/opt/lool/child-roots/Il1oS2dgPsdODGa9/lo] failed: Permission denied.
Sep 25 15:27:43 vnclpb1 loolwsd[14250]: kit-15573-14256 2020-09-25 13:27:43.627610 [ kit_spare_003 ] ERR  Failed to unmount [/opt/lool/child-roots/Il1oS2dgPsdODGa9/lo].| common/JailUtil.cpp:70
Sep 25 15:27:43 vnclpb1 loolwsd[14250]: /usr/bin/loolmount: forced unmount of [/opt/lool/child-roots/XuuVkTQOzdi6lfl4/lo] failed: Permission denied.
Sep 25 15:27:43 vnclpb1 loolwsd[14250]: kit-15574-14256 2020-09-25 13:27:43.642396 [ kit_spare_004 ] ERR  Failed to unmount [/opt/lool/child-roots/XuuVkTQOzdi6lfl4/lo].| common/JailUtil.cpp:70
Sep 25 15:27:43 vnclpb1 systemd[15367]: opt-lool-child\x2droots-Il1oS2dgPsdODGa9.mount: Succeeded.
Sep 25 15:27:43 vnclpb1 systemd[1]: opt-lool-child\x2droots-Il1oS2dgPsdODGa9.mount: Succeeded.
Sep 25 15:27:43 vnclpb1 loolwsd[14250]: /usr/bin/loolmount: forced unmount of [/opt/lool/child-roots/Il1oS2dgPsdODGa9] failed: Permission denied.
Sep 25 15:27:43 vnclpb1 loolwsd[14250]: kit-15573-14256 2020-09-25 13:27:43.661583 [ kit_spare_003 ] ERR  Failed to unmount [/opt/lool/child-roots/Il1oS2dgPsdODGa9/].| common/JailUtil.cpp:70
Sep 25 15:27:43 vnclpb1 systemd[15367]: opt-lool-child\x2droots-XuuVkTQOzdi6lfl4.mount: Succeeded.
Sep 25 15:27:43 vnclpb1 systemd[1]: opt-lool-child\x2droots-XuuVkTQOzdi6lfl4.mount: Succeeded.
Sep 25 15:27:43 vnclpb1 loolwsd[14250]: /usr/bin/loolmount: forced unmount of [/opt/lool/child-roots/XuuVkTQOzdi6lfl4] failed: Permission denied.
Sep 25 15:27:43 vnclpb1 loolwsd[14250]: kit-15574-14256 2020-09-25 13:27:43.697419 [ kit_spare_004 ] ERR  Failed to unmount [/opt/lool/child-roots/XuuVkTQOzdi6lfl4/].| common/JailUtil.cpp:70
```
and in the host system (Proxmox VE 6):
```
Sep 25 15:27:42 ino kernel: [433028.908691] audit: type=1400 audit(1601040462.792:24): apparmor="DENIED" operation="mount" info="failed flags match" error=-13 profile="lxc-104_</var/lib/lxc>" name="/opt/lool/child-roots/ridzJ5vsTwBcah6P/" pid=3673 comm="loolmount" flags="ro, nosuid, nodev, remount, noatime, rbind, silent"
Sep 25 15:27:43 ino kernel: [433029.669132] audit: type=1400 audit(1601040463.552:25): apparmor="DENIED" operation="mount" info="failed flags match" error=-13 profile="lxc-104_</var/lib/lxc>" name="/opt/lool/child-roots/Il1oS2dgPsdODGa9/" pid=3813 comm="loolmount" flags="ro, nosuid, nodev, remount, noatime, rbind, silent"
Sep 25 15:27:43 ino kernel: [433029.676506] audit: type=1400 audit(1601040463.560:26): apparmor="DENIED" operation="mount" info="failed flags match" error=-13 profile="lxc-104_</var/lib/lxc>" name="/opt/lool/child-roots/XuuVkTQOzdi6lfl4/" pid=3814 comm="loolmount" flags="ro, nosuid, nodev, remount, noatime, rbind, silent"
```
I've tried to disable options like 'mount_jail_tree' and 'capabilities' with no luck.

Collabora Online is incompatible with unprivileged containers?!

Thanks.

**Comment by marcogaio** [comment]
Some interesting discussion on:
https://help.nextcloud.com/t/loolwsd-and-unprivileged-lxc-containers/93460/8

but still no clue.

**Comment by nibelungen** [comment]
Really no solution so far?? Follow official guidelines and still no support? Not the best promotion for Collabora and Nextcloud in Containers...

Here is what i get if i want to open or create a document:

`
cloud-app     | 2020-11-05T09:15:43.772914636Z 172.19.0.4 - - [05/Nov/2020:09:15:43 +0000] "GET /core/preview?fileId=646606&c=4858ff5875aac4995f531292f402e699&x=250&y=250&forceIcon=0 HTTP/1.1" 404 730 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36"
cloud-app     | 2020-11-05T09:15:47.595016948Z 172.19.0.4 - - [05/Nov/2020:09:15:47 +0000] "GET /apps/richdocuments/index?fileId=646606&requesttoken=n5mm%2FuJyesqbpSG5Q5bgx9KFbVV<<stripped>> HTTP/1.1" 200 7115 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36"
cloud-app     | 2020-11-05T09:15:48.054669746Z 172.19.0.4 - - [05/Nov/2020:09:15:47 +0000] "GET /cron.php HTTP/1.1" 200 895 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36"
collabora-app | 2020-11-05T09:15:48.538135706Z wsd-00006-00056 2020-11-05 09:15:48.537942 [ docbroker_002 ] WRN  File system of [/opt/lool/child-roots/.] is dangerously low on disk space.| wsd/LOOLWSD.cpp:309
collabora-app | 2020-11-05T09:15:48.539306816Z frk-00038-00038 2020-11-05 09:15:48.539125 [ forkit ] ERR  Failed to get the realpath of [/etc/timezone] (ENOENT: No such file or directory)| common/FileUtil.cpp:256
collabora-app | 2020-11-05T09:15:48.539497783Z frk-00038-00038 2020-11-05 09:15:48.539224 [ forkit ] ERR  Failed to get the realpath of [/etc/localtime] (ENOENT: No such file or directory)| common/FileUtil.cpp:256
cloud-app     | 2020-11-05T09:15:48.625561372Z 172.19.0.4 - - [05/Nov/2020:09:15:48 +0000] "GET /index.php/apps/richdocuments/wopi/files/646606_ocxd404xhwld?access_token=0qzCmXwVs2UbA0rDHu<<stripped>>&access_token_ttl=0 HTTP/1.1" 200 1875 "-" "LOOLWSD WOPI Agent 6.4.0"
cloud-app     | 2020-11-05T09:15:48.715723261Z 172.19.0.4 - - [05/Nov/2020:09:15:48 +0000] "GET /index.php/apps/richdocuments/wopi/files/646606_ocxd404xhwld/contents?access_token=0qzCmXwVs2UbA0rDHu9<<stripped>>&access_token_ttl=0 HTTP/1.1" 200 1986 "-" "LOOLWSD WOPI Agent 6.4.0"
collabora-app | 2020-11-05T09:15:48.716610578Z wsd-00006-00056 2020-11-05 09:15:48.716504 [ docbroker_002 ] WRN  File system of [/opt/lool/child-roots/.] is dangerously low on disk space.| wsd/LOOLWSD.cpp:309
collabora-app | 2020-11-05T09:15:48.853642460Z kit-00057-00038 2020-11-05 09:15:48.853493 [ kit_spare_003 ] ERR  Failed to get the realpath of [/etc/timezone] (ENOENT: No such file or directory)| common/FileUtil.cpp:256
collabora-app | 2020-11-05T09:15:48.853832573Z kit-00057-00038 2020-11-05 09:15:48.853668 [ kit_spare_003 ] ERR  Failed to get the realpath of [/etc/localtime] (ENOENT: No such file or directory)| common/FileUtil.cpp:256
collabora-app | 2020-11-05T09:15:49.090012894Z wsd-00006-00056 2020-11-05 09:15:49.089874 [ docbroker_002 ] WRN  Client session [015] not found to forward message: o53 status: type=spreadsheet parts=1 current=0 width=26771 height=13005 viewid=0...| wsd/DocumentBroker.cpp:2251
collabora-app | 2020-11-05T09:15:49.090140121Z wsd-00006-00056 2020-11-05 09:15:49.090065 [ docbroker_002 ] WRN  Client session [015] not found to forward message: o55 editor: -1| wsd/DocumentBroker.cpp:2251
collabora-app | 2020-11-05T09:15:49.090728108Z wsd-00006-00056 2020-11-05 09:15:49.090178 [ docbroker_002 ] WRN  Client session [015] not found to forward message: o56 statusindicatorstart:| wsd/DocumentBroker.cpp:2251
collabora-app | 2020-11-05T09:15:49.091125605Z wsd-00006-00056 2020-11-05 09:15:49.091048 [ docbroker_002 ] WRN  Client session [015] not found to forward message: o57 statusindicatorfinish:| wsd/DocumentBroker.cpp:2251
collabora-app | 2020-11-05T09:15:49.091284343Z wsd-00006-00056 2020-11-05 09:15:49.091125 [ docbroker_002 ] WRN  Client session [015] not found to forward message: o58 statusindicatorfinish:| wsd/DocumentBroker.cpp:2251
collabora-app | 2020-11-05T09:15:49.091319344Z wsd-00006-00056 2020-11-05 09:15:49.091190 [ docbroker_002 ] WRN  Client session [015] not found to forward message: o59 signaturestatus: 0| wsd/DocumentBroker.cpp:2251
collabora-app | 2020-11-05T09:15:49.092034135Z wsd-00006-00056 2020-11-05 09:15:49.091827 [ docbroker_002 ] WRN  Client session [015] not found to forward message: o60 disconnected:| wsd/DocumentBroker.cpp:2251
collabora-app | 2020-11-05T09:15:49.583401557Z sh: 1: /usr/bin/loolmount: Operation not permitted
collabora-app | 2020-11-05T09:15:49.583883481Z frk-00038-00038 2020-11-05 09:15:49.583527 [ forkit ] ERR  Failed to unmount [/opt/lool/child-roots/qQr4maCziuD3Fo7s/tmp].| common/JailUtil.cpp:68
collabora-app | 2020-11-05T09:15:49.612360587Z sh: 1: /usr/bin/loolmount: Operation not permitted
collabora-app | 2020-11-05T09:15:49.612516135Z frk-00038-00038 2020-11-05 09:15:49.612403 [ forkit ] ERR  Failed to unmount [/opt/lool/child-roots/qQr4maCziuD3Fo7s/lo].| common/JailUtil.cpp:68
collabora-app | 2020-11-05T09:15:49.630456582Z sh: 1: /usr/bin/loolmount: Operation not permitted
collabora-app | 2020-11-05T09:15:49.631004185Z frk-00038-00038 2020-11-05 09:15:49.630857 [ forkit ] ERR  Failed to unmount [/opt/lool/child-roots/qQr4maCziuD3Fo7s].| common/JailUtil.cpp:68
`
Error Message in Frontend:
![image](https://user-images.githubusercontent.com/1270854/98222847-abcbbc00-1f51-11eb-9fdc-5d72d3efa4cc.png)


**Sysinfo:**
DB: mysql
Version: 10.5.7
PHP: 7.4.12
Nextcloud: 20.0.1
Collabora Online App: 3.7.6
Community Document Server: 0.1.8
Docker: 19.03.12, build 48a66213fe
Docker Images: mariadb:latest, nextcloud:latest, collabora/code
Diskspace: 198G Free


Any help apreciated, thanks in advance

**Comment by marcogaio** [comment]
OK, is seems it suffices to enable on PVE container the 'nesting' options (nesting=1) as for:
  https://pve.proxmox.com/pve-docs/pve-admin-guide.html#pct_configuration

I keep the bur report open for further comment, eg security implication.

Thanks.

**Comment by foobn** [comment]
Is there any update on this topic? Facing the same problems. Collabora Online is running but I only get a blank page when opening documents.

**Comment by marcogaio** [comment]
I can confirm that it sufficies to have 'nesting=1' in container configuration to let LOOL work as expected.
Still i get some 'mount' errors in logs, but works.

Most of my trouble come from an erratic/imperfect virtualhost configuration, mostly done by trial and error before settings 'nestiung=1'.

**Comment by timar** [comment]
Those 'mount' errors are not severe, the app tries to mount, and when it fails, it tries to link or copy.
