### ISSUE TITLE
Cannot install Collabora Online - Built-in CODE Server (ARM64) from web interface

### ISSUE THREAD

**Issue by sharicov** [CollaboraOnline/richdocumentscode#73]
Getting error:
cURL error 28: Operation timed out after 120000 milliseconds with 120972765 out of 407903292 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)
Running on raspberry pi4 with yunohost 4.0.8
Nextcloud version: 19.0.3~ynh1

**Comment by sharicov** [comment]
solved by increasing timeout in /var/www/nextcloud/lib/private/Installer.php from 120 to 3000

**Comment by garrett** [comment]
I was hitting this bug as well. Locally editing a file in lib/private is a workaround, not an actual fix.

(If this were actually fixed in September, I wouldn't have hit it today.)
