### ISSUE TITLE
Could not establish connection to the Collabora Online server.

### ISSUE THREAD

**Issue by sharicov** [CollaboraOnline/richdocumentscode#74]
Installed Collabora Online and Collabora Online - Built-in CODE Server (ARM64)
running in yunohost server (not docker) on raspberry Pi 4
opened 9980 port
in Collabora Online settings providing https://MyExternalDomainName:9980
Gettting error:
Could not establish connection to the Collabora Online server.

**Comment by timar** [comment]
Built-in CODE server uses port 9983. But it's better to set it up via `settings/admin/richdocuments`.
