### ISSUE TITLE
freeze row and columns

### ISSUE THREAD

**Issue by ferdiga** [CollaboraOnline/richdocumentscode#76]
Hi!
according to the collabora office 6.0 
![image](https://user-images.githubusercontent.com/6248560/94828752-16954f00-040a-11eb-82e9-a94ee54f947a.png)

https://www.collaboraoffice.com/code-6-4-release-notes/
and
https://www.collaboraoffice.com/press-releases/code-6-4-0-release/
**"New Spreadsheet rendering: freeze rows and columns"**
should be available

IMHO it would be great to migrate the 6.4 CODE to nextcloud app as the "freeze rows and columns" is mandatory for working in spread sheets greater one window screen.
thanks for looking into this.

**Comment by thebearon** [comment]
Yes, that's the plan.

**Comment by ferdiga** [comment]
+++

**Comment by timar** [comment]
We released the CODE 6.4 based app.
