### ISSUE TITLE
Document view randomly jumps back and forth

### ISSUE THREAD

**Issue by EDRi-org** [CollaboraOnline/richdocumentscode#78]
We're using Collabora CODE with Nextcloud and experience a weird issue:
As soon as more than one user edits a rich text document collaboratively, the page view of each user jumps from where the cursor is back to the top of the document. When the user makes any keyboard entry, the page view jumps back to the cursor position. Unfortunately, this makes collaborative editing of documents quite unusable.
Has anyone seen this behaviour elsewhere and could this be a bug?

**Collabora Office 6.4-5** (git hash: bd7e2b2) on CentOS 8 (from official repo)
**Nextcloud 19.0.3** on a separate CentOS 7 server

Please let me know if you need additional information. Thanks!

**Comment by mmeeks** [comment]
Strange - we co-edit documents every day; what would really help is a sample document, and/or a video of this.
Also - if you go to Help->About and tripple-click, you should end up in a debug mode.
If you can paste the output from the console after one of those switches it should really help.
Beyond that turning debugging up to 'trace' in loolwsd.xml and re-starting / reproducing would help if we could get compressed logs.

Thanks !

**Comment by EDRi-org** [comment]
Thanks for the quick response @mmeeks! Here is a sample document on our server: https://cloud.edri.org/index.php/s/4PCCrpAkziNKecd
I will try to gather a couple of colleagues on Monday to do some testing with debugging mode switched on and paste the results here.

**Comment by timar** [comment]
This bug report rather belongs to CollaboraOnline/online project. Anyhow, we fixed a few document jumping issues in the past few month. If problem persists, please open a new issue at CollaboraOnline/online.
