### ISSUE TITLE
You don't have permission to access /custom_apps/richdocumentscode/proxy.php on this server.

### ISSUE THREAD

**Issue by PipeItToDevNull** [CollaboraOnline/richdocumentscode#79]
Running Nextcloud 19.0.4-Apache on Docker with JWilder reverse proxy container.

When loading up a .odt I receive this error. In the settings for Collabora online I have a connection to the CODE server.

I dont understand what this error actually means so I am not sure where to start troubleshooting it.

**Comment by itsthejb** [comment]
Check the error carefully: mine has the URL as `https://nextcloud/custom_apps/richdocumentscode/proxy.php?status`. This is the docker container name, so seems like need to point it properly to my domain name. You may have the same issue

**Comment by itsthejb** [comment]
Might be related to https://github.com/CollaboraOnline/richdocumentscode/issues/2

**Comment by timar** [comment]
Please reopen, if it's still reproducible.
