### ISSUE TITLE
Exception: App "Collabora Online - Built-in CODE Server (ARM64)" cannot be installed because the following dependencies are not fulfilled: The following architectures are supported: aarch64

### ISSUE THREAD

**Issue by Larsene** [CollaboraOnline/richdocumentscode#81]
Hi,

I have this error when i tried to install the Build-in CODE serveur (ARM64) on a Raspberry Pi4 8Go (NextCloudPi).

**Comment by sunjam** [comment]
Are you running the armhf version of NextcloudPi?  Check under 4443 for system report from nc-info

Just succeeded for me on an Odroid device as of 4.2.900

**Comment by Larsene** [comment]
Hmmm, i didn't see that information in nc-info ...

Gathering information...
NextCloudPi version  v1.30.0
NextCloudPi image    NextCloudPi_12-20-19
distribution         Raspbian GNU/Linux 10 \n \l
automount            yes
USB devices          sda sdb
datadir              /var/www/nextcloud/data
data in SD           yes
data filesystem      ext2/ext3
data disk usage      348G/917G
rootfs usage         348G/917G
swapfile             /var/swap
dbdir                /var/lib/mysql
Nextcloud check      ok
Nextcloud version    20.0.0.9
HTTPD service        up
PHP service          up
MariaDB service      up
Redis service        up
Postfix service      up
internet check       ok
port check 80        closed
port check 443       closed
IP                   172.20.90.41
gateway              172.20.90.254
interface            eth0
certificates         *ic.com
NAT loopback         no
uptime               2days

**Comment by bcutter** [comment]
On my Raspberry Pi 4 it seems to be installed fine:

```
sudo -u www-data php /var/www/nextcloud/occ app:install richdocumentscode_arm64
richdocumentscode_arm64 installed
richdocumentscode_arm64 enabled
```
...BUT the CODE server is not showing up as option on https://my-nextcloud-server.org/index.php/settings/admin/richdocuments page...! Only "Use your own server" and "Use a demo server".

**What to check next? Seems like app "richdocuments" is not aware of installed "richdocumentscode_arm64" app...**

**Comment by sunjam** [comment]
Please paste output of `$ dpkg --print-architecture`

**Comment by bcutter** [comment]
> 
> 
> Please paste output of `$ dpkg --print-architecture`

armhf

**Comment by bcutter** [comment]
One idea: why can´t the richdocumentscode_arm64 app **check the dependencies (at least by doing what I did: "dpkg --print-architecture" and compare with a internal whitelist) during installation?**

Users like me are trapped and waste a lot of time finding out the app isn´t working even everything looks like it is.

**Comment by sunjam** [comment]
Well, perhaps that may happen (I have no idea), but it is up to you to install an arm64 operating system.  Raspberry Pi is just barely getting caught up with their software, despite offering an 8gb ram arm64 device for some time.

**Comment by Larsene** [comment]
You can force enable ARM64 in the **config.txt** of your raspberry Pi, by adding **arm_64bit=1**. Then, every options are here.

but, another problem is reported by richdocumentscode , when you check the status of the CODE Server : 

`https://nextcloud.***.com/apps/richdocumentscode_arm64/proxy.php?status`

report : `{"status":"error","error":"no_glibc"}`

even if `ldd --version` report : 

```
ldd (Debian GLIBC 2.28-10+rpi1) 2.28
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

**Comment by bcutter** [comment]
"arm_64bit=1"

That sounds a bit too brave to me as it's only the second of a two step operation (first is pulling latest dev kernel using rpi-update). It can't work I guess. I think we need to wait for a stable release of 64 bit Raspberry Pi OS. Until that mixing a beta x64 OS with a productive Nextcloud environment doesn't sound like a good idea (and a solid base for the office integration) to me.

But back to topic...

**Comment by Ivar418** [comment]
u have to install 64bit debian for all this to work (i done it yesterday and it seems to work....kinda)  

https://www.raspberrypi.org/forums/viewtopic.php?t=275370

**Comment by Ivar418** [comment]
> 
> 
> "arm_64bit=1"
> 
> That sounds a bit too brave to me as it's only the second of a two step operation (first is pulling latest dev kernel using rpi-update). It can't work I guess. I think we need to wait for a stable release of 64 bit Raspberry Pi OS. Until that mixing a beta x64 OS with a productive Nextcloud environment doesn't sound like a good idea (and a solid base for the office integration) to me.
> 
> But back to topic...

i mean. it works, performance of the beta 64bit is 100x better than the 32 bit version of debian. ive had no issues so far that are realted to debain being 64bit

**Comment by sunjam** [comment]
If you need 64-bit Raspbian

http://downloads.raspberrypi.org/raspios_lite_arm64/

**Comment by Larsene** [comment]
raspberry ARM64 install is required : [RaspiOS 64bit Lite](http://downloads.raspberrypi.org/raspios_lite_arm64/)
tested and working.

**Comment by Timsuper** [comment]
Thanks guys. Guess we'll have to wait. :S

**Comment by Ivar418** [comment]
> 
> 
> Thanks guys. Guess we'll have to wait. :S

no u can already use arm64 ive been using it for about a month now with nextcloud and i have had 0 issues

**Comment by bcutter** [comment]
> > 
> 
> > 
> 
> > Thanks guys. Guess we'll have to wait. :S
> 
> 
> 
> no u can already use arm64 ive been using it for about a month now with nextcloud and i have had 0 issues

Yes but
- it's not stable yet (still beta)
- there's no simple switch/upgrade. You have to start from scratch which is a no-go for me.

😕

**Comment by Larsene** [comment]
> * it's not stable yet (still beta)
Right. But you can use Ubuntu if you prefer.
> * there's no simple switch/upgrade. You have to start from scratch which is a no-go for me.
there won't be one. Switching from 32 to 64 bit OS require a complete reinstall.

**Comment by Timsuper** [comment]
> * it's not stable yet (still beta)
>   Right. But you can use Ubuntu if you prefer.
> * there's no simple switch/upgrade. You have to start from scratch which is a no-go for me.
>   there won't be one. Switching from 32 to 64 bit OS require a complete reinstall.

Technically there is a way to just switch the Kernel from 32 to 64. But it didn’t work. I mean, you don’t want to mess up your NC installation, right?

**Comment by Ivar418** [comment]
> > * it's not stable yet (still beta)
> >   Right. But you can use Ubuntu if you prefer.
> > * there's no simple switch/upgrade. You have to start from scratch which is a no-go for me.
> >   there won't be one. Switching from 32 to 64 bit OS require a complete reinstall.
> 
> Technically there is a way to just switch the Kernel from 32 to 64. But it didn’t work. I mean, you don’t want to mess up your NC installation, right?

Switching kernel wont change anything, ud also need 64 bit packages

**Comment by vantino** [comment]
Ciao - I face the same problem as described here, with

dpkg --print-architecture
armhf

and 

{"status":"error","error":"no_glibc"}

Is there any procedure to upgrade the 64bit packages without reinstalling the OS. ?

???

**Comment by Ivar418** [comment]
> Ciao - I face the same problem as described here, with
> 
> dpkg --print-architecture
> armhf
> 
> and
> 
> {"status":"error","error":"no_glibc"}
> 
> Is there any procedure to upgrade the 64bit packages without reinstalling the OS. ?
> 
> ???

I think you can. If you add the repos for the 64 bit version of the packages to apt soursec. But i dont know the outcome

**Comment by sunjam** [comment]
Make sure your device actually supports arm64 and has at least 4gb ram.
Then, backup your Nextcloud data, install arm64 image, and restore
Nextcloud.

**Comment by Larsene** [comment]
wrong answer : this should print arm64, not armh. You have to reinstall a 64bit OS.

> Ciao - I face the same problem as described here, with
> 
> dpkg --print-architecture
> armhf

**Comment by vantino** [comment]
Thanks.

how do I reinstall a 64bit os without deleting all my configurations. applications, etc.?
does that mean i have to do a completely new setup of the maschine? which kind of huge effort.

would be happy to get instructuions or links to a tutorial to upgrade to arm64 w/o reinstalling all my app*s like mysql, php, apache2, pi-hole, samba and all the other stuff.

**Comment by sunjam** [comment]
arm64 image means OS / Distribution / iso for your specific device,
assuming it does actually support this architecture. Thanks for clarifying
if it was confusing.

**Comment by Larsene** [comment]
@vantino : as said in this thread, you HAVE TO reinstall your all system, then all your app. This is a major change !

**Comment by vantino** [comment]
FInally, I did a new setup of my rpi4 with arm64 packages only. I am running now a arm64 box and enjoy
- tested 30% i/o operations with my M2 SSD on USB3
- it feels like reaction time of app's is pretty faster
- server app's like minidlna, web, wordpress, etc too
- and finally, collabora-online and collabora-code works in my nextcloud application

Thanks for feedback & assistance
