### ISSUE TITLE
Failed to load Collabora Online - please try again later✖

### ISSUE THREAD

**Issue by sunjam** [CollaboraOnline/richdocumentscode#82]
Armbian 20.08.3 Buster with Linux 5.8.10-meson64 on Odroid C2 with 2gb ram.
NextcloudPi 20.0.0 with Collabora 4.2.900

Installations now succeeds (!), but unable to actually open files after creation in Files app.
`Failed to load Collabora Online - please try again later✖`

Error | richdocuments | Exception: Could not find urlsrc in WOPI/data/nextcloud/apps/richdocuments/lib/TokenManager.php - line 210: OCA\Richdocuments\WOPI\Parser->getUrlSrc("application ... t")/data/nextcloud/apps/richdocuments/lib/Controller/DocumentController.php - line 256: OCA\Richdocuments\TokenManager->getToken("*** sensiti ... *")/data/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 169: OCA\Richdocuments\Controller\DocumentController->index("*** sensiti ... *", null)/data/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 100: OC\AppFramework\Http\Dispatcher->executeController(OCA\Richdocu ... {}, "index")/data/nextcloud/lib/private/AppFramework/App.php - line 152: OC\AppFramework\Http\Dispatcher->dispatch(OCA\Richdocu ... {}, "index")/data/nextcloud/lib/private/Route/Router.php - line 308: OC\AppFramework\App::main("OCA\\Richdo ... r", "index", OC\AppFramew ... {}, { action: nu ... "})/data/nextcloud/lib/base.php - line 1009: OC\Route\Router->match("/apps/richdocuments/index")/data/nextcloud/index.php - line 37: OC::handleRequest()
-- | -- | --

**Comment by timar** [comment]
Seems to be same as https://github.com/nextcloud/richdocuments/issues/1442

**Comment by timar** [comment]
Would you mind re-testing with version 6.4.705?

**Comment by gitgt** [comment]
Since there was no response here and rather old, I close.
