### ISSUE TITLE
Cannot run from shared host

### ISSUE THREAD

**Issue by robert-winkler** [CollaboraOnline/richdocumentscode#83]
Hi, running from a demo host works fine, but using the built-in CODE server results in:

Cannot connect to server; or cannot start Collabora please try later.

Looking into detail:

~/nextcloud/apps/richdocumentscode/collabora$ ./Collabora_Online.AppImage --appimage-extract-and-run
Failed to run /tmp/appimage_extracted_fc2c2b2b6e07c84d07ea688eb3e1c660/AppRun: Permission denied

Is this a problem when running on a shared host?

**Comment by timar** [comment]
Unfortunately, if execution of binaries is not allowed, then the app is unusable.
