### ISSUE TITLE
Nextcloud in dark mode (accessibility setting) causes white unseeable icons

### ISSUE THREAD

**Issue by CactiChameleon9** [CollaboraOnline/richdocumentscode#87]
Screenshot of bug:
![image](https://user-images.githubusercontent.com/51231053/97168375-3f4a0380-1780-11eb-9012-53346e1ec4a3.png)

**Comment by AmonBune** [comment]
Providing a dark theme for Collabora Online would be the real solution, but fixing the icons in the meantime is a good idea.

I use the dark theme all the time so I suffer from this bug.

**Comment by timar** [comment]
I tried to reproduce the bug but I could not. I set the Dark theme at `settings/user/accessibility`. I'm using Nextcloud 20 and richdocumentscode 6.4.703

**Comment by nursoda** [comment]
Icons are fine here, too: Arch, Dark theme, NC21, RDC 6.4.705

**Comment by timar** [comment]
I close this then. Please re-open, if you have further evidence.
