### ISSUE TITLE
 Kubernetes (Docker) + Built-in Code server || proxy.php "sh: disown: not found" on Debian

### ISSUE THREAD

**Issue by Alfablos** [CollaboraOnline/richdocumentscode#91]
Hello,
I've recently set up a nextcloud instance in Kubernetes via helm chart.
When I tried to install collabora (CODE server + Collabora online) I got several errors but since none of them was actually showing useful information I turned on the logs within proxy.php
```
    error_log($msg);
```
The error which I though was most important was the one in the title:
`sh: disown: not found`

The function `startLoolwsd()` is called at [proxy.php:202](https://github.com/CollaboraOnline/richdocumentscode/blob/1070c19ffc82b0b422851779640b5f46a2a62604/proxy.php#L202) and it invokes the exec() builtin. The PHP builtin appears to run che command using `/bin/sh` which doesn't have the disown shell builtin. so while the `startLoolwsd()` function actually starts the collabora appimage with `$appImage --appimage-extract-and-run &` to have it run in background but I'm guessing the rest of the script runs as if the function had returned a non 0 exit code (sorry, I'm not a PHP expert) since the actual command fails due to the disown part.
The result is that when you open a document you get an exit code of 99 and, of course if you try to manually run in a shell
```
./$collabora_appimage_filename --appimage-extract-and-run
```
the command fails because the 9982 port is already in use by the previous same command.

My solution was to use `nohup` in place of `disown`
```
$launchCmd = "( $appImage || nohup $appImage --appimage-extract-and-run > /var/www/html/data/richdocumentscode_collabora.log) > /dev/null 2>&1";
```

This seems to work like a charm but maybe there's a cleaner way to run this container-compatible strategy, so I'm opening this issue.

About my configuration:
```
$ kubectk version
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.13-dispatcher", GitCommit:"fd22db44e150011eccc8729db223945384460143", GitTreeState:"clean", BuildDate:"2020-07-24T07:48:37Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-09T11:18:22Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}

### Kubernetes Nodes ###
$ sudo docker version
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:45:44 2020
 OS/Arch:           linux/amd64
 Experimental:      false
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.40/version: dial unix /var/run/docker.sock: connect: permission denied
kube@knode1:~$ sudo !!
sudo docker version
[sudo] password for kube:
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:45:44 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:44:15 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683


$ dpkg -l |awk '{print $2,$3}' | grep -iE "(kube.+|docker.+|containerd)"
containerd.io 1.2.13-2
docker-ce 5:19.03.12~3-0~ubuntu-focal
docker-ce-cli 5:19.03.12~3-0~ubuntu-focal
kubeadm 1.19.1-00
kubectl 1.19.1-00
kubelet 1.19.1-00
kubernetes-cni 0.8.7-00

$ helm version     # Helm values.yaml attached to the message
version.BuildInfo{Version:"v3.4.0", GitCommit:"7090a89efc8a18f3d8178bf47d2462450349a004", GitTreeState:"dirty", GoVersion:"go1.15.3"}

$ helml list -A    #I'm actually using the 20-fpm image for Nextcloud
NAME     	NAMESPACE	REVISION	UPDATED                             	STATUS  	CHART          	APP VERSION
nextcloud	nextcloud	2       	2020-11-06 23:14:19.738228 +0100 CET	deployed	nextcloud-2.2.1	19.0.3

### I had to edit the entrypoint (mounted as a configMap volume) in order to add the smbclient package. Maybe I'll generate a custom image but I think it's fine to keep it like this for now since it takes less than the initialDelaySeconds for the readiness/liveness probes.

```

Attachments:
nextcloud-values.yaml # Helm values
00_requirements.yaml # Kubernetes objects for storage and entrypoint.sh as configmap

Thanks guys! Your app is awesome! 

[collaboracode-issue-kubernetes-helm-config.tar.gz](https://github.com/CollaboraOnline/richdocumentscode/files/5504775/collaboracode-issue-kubernetes-helm-config.tar.gz)

**Comment by timar** [comment]
Hopefully it's been fixed by 0d68541866fef033de17910e0a3841771794e02d
