### ISSUE TITLE
Download failed with error 23

### ISSUE THREAD

**Issue by NoDiskNoFun** [CollaboraOnline/richdocumentscode#96]
Hey there,

i just setup up a new Nextcloud instance inside a systemd-nspawn container. I also wanted to add the CODE server for reasons but everytime i try to download it i recieve:

sudo -u http php -d memory_limit=512M occ app:install richdocumentscode_arm64

[Wait for about 15 Min ...]

Error: cURL error 23: Failure writing output to destination (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)

I've used the command line tool occ, like its recommended in the ReadMe.

Any suggestions? Could this because its inside nspawn or maybe because i mount-bind folders inside data? But i did mount-bind the folders to usernames for example /RAID/.Nextcloud/lukas to /usr/share/webapps/nextcloud/data/lukas. Also i checked the free Space which is 50GB. Should be enough ...

Thanks in advance.
Lukas aka NoDiskNoFun

**Comment by urusai-me** [comment]
Maybe you can manually install. All you need is download the release file and decompress them into your `NEXTCLOUD/apps/` directory, then make sure permission are correctly managed.
